### ISSUE TITLE
Cannot run tests on Windows because drive letter is passed in lowercase to the command

### ISSUE THREAD

**Issue by xrnoz** [vitest-dev/vscode#100]
**Describe the bug**
Cannot run tests on windows because drive letter is passed in lowercase and the tests are not found, I can see in the terminal the resulting command `vitest dev --config=tests/vitest.dev.ts d:/<redacted> --api.port 50062 --api.host 127.0.0.1`, if I use that command in another terminal the tests are also not found but just changing the drive letter from lowercase to uppercase makes the tests to be found and able to run, e.j. `vitest dev --config=tests/vitest.dev.ts D:/<redacted> --api.port 50062 --api.host 127.0.0.1`

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Go to 'Testing'
2. Click on 'Run Tests'
3. Scroll down to 'Output > Vitest'
4. See error: Test not found: file:///d%3A/Development/vitest-ext-basic-example/add.test.ts/add 1 + 1@1

In the example project I can see in Output > Vitest, that the command is run like this: `./node_modules/.bin/vitest d:/Development/vitest-ext-basic-example/add.test.ts`. In another terminal if I run `.\node_modules\.bin\vitest d:/Development/vitest-ext-basic-example/add.test.ts` the test is also not found, but if I change the drive letter to uppercase, the test is found:

```
D:\Development\vitest-ext-basic-example>.\node_modules\.bin\vitest D:/Development/vitest-ext-basic-example/add.test.ts

 DEV  v0.12.10 D:/Development/vitest-ext-basic-example

 √ add.test.ts (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.22s (in thread 5ms, 24482.28%)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

**Expected behavior**
Tests run.

**Screenshots**
![2022-11-10 14_53_25](https://user-images.githubusercontent.com/7775099/201193209-75e6e54c-51f1-459e-bb43-2e3f015691c1.png)
![2022-11-10 14_54_22-Window](https://user-images.githubusercontent.com/7775099/201193232-5ca41d93-54f5-40d0-b1e2-94572f467c24.png)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: Windows 10
- VSCode version: 1.73.1
- Vitest version: "vitest@0.25.1" in my project, vitest@"^0.12.6" in example
- Vitest plugin version: v0.2.32

**Additional context**

**Comment by zxch3n** [comment]
Thanks for reporting this. Fixed in v0.2.33
