### ISSUE TITLE
无法解析正确的测试文件.

### ISSUE THREAD

**Issue by cweijan** [vitest-dev/vscode#106]
英语比较糟糕, 就用中文说了.
在代码[vscodeUtils](https://github.com/vitest-dev/vscode/blob/main/src/vscodeUtils.ts#L20)中, 路径匹配具有严重的错误, 这导致如果Test explorer还没加载, 打开单个测试文件永远无法解析到, 因为它总是返回false.

复现流程:
1. 重启VSCode, 不激活Test explorer
2. 打开任意一个测试文件(此时无法解析)
3. 如果屏蔽掉这段代码, 使用以上两步则可以正常解析.

**Comment by zxch3n** [comment]
无法复现该问题。单个测试文件是属于当前打开的项目目录下的吗？你是否有全局的 vscode vitest 的设置？
