### ISSUE TITLE
 In Windows, vscode is started for the first time. The vitest tool does not start normally.

### ISSUE THREAD

**Issue by RSS1102** [vitest-dev/vscode#107]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

**Expected behavior**

If I have installed 'vitest', the 'vitest' icon should be displayed on the side when I start 'vscode'.

**Screenshots**
![image](https://user-images.githubusercontent.com/81673017/205872134-d3a89bdd-e8cf-45c5-953c-12969a16fc45.png)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: [e.g. macOS]
- VSCode version:
版本: 1.73.1 (user setup)
提交: 6261075646f055b99068d3688932416f2346dd3b
日期: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: No
- Vitest version:v0.2.34

- Vitest plugin version:"vitest": "^0.22.1",

**Additional context**

**The side tool can only be displayed if I manually disable the vitest and then enable it again.**

**Comment by JAKimball** [comment]
When this happens do you find the following string in the "Extension Host" or "Remote Extension Host" logs? (In the "OUTPUT" tab of the panel.)

`Not activating extension 'ZixuanChen.vitest-explorer': Timed out while searching for 'workspaceContains' pattern **/vitest.config.*s,**/vite.config.*s,**/package.json`

This is what I see whenever this happens.
