### ISSUE TITLE
Not working correctly when using data tables ( Test Visualization in  Side Bar )

### ISSUE THREAD

**Issue by delight** [vitest-dev/vscode#108]
**Describe the bug**
Given: Using vitest unit tests with datatables 
Expectation: Show test as failed if 1 of them fails 
Ideal: Unroll Tests and show the ones that failed

Status: 
- Shows test  as **Failed** only if the first entry of the DataTable leads to a failed test. 
- Otherwise shows them as **Passed**.

Note:
- Test failures and number of unrolled tests are shown correctly in console (vitest).
- Test failures and number of unrolled tests are shwon correctly in the vscode status bar.

**To Reproduce**

- for the following method:
```ts

const capitalize = (str: string): string => {
    return str.charAt(0).toUpperCase() + str.slice(1);
}
```

1. Write an unit test with data-tables e.g.
```ts
import { test, describe, expect } from "vitest";

describe('should capitalize the first character of a string', () => {

    const dataTable = [
        { input: 'hello', expected: 'Hello' },
        { input: 'world', expected: 'World' },
        { input: '', expected: '' },
        { input: '123', expected: '123' },
    ];

    dataTable.forEach(({ input, expected }) => {
        test(`capitalizes the first character of '${input}' => '${expected}'`, () => {
            expect(capitalize(input)).toBe(expected);
        });
    });
});
```
2) let one of the test fail.

**Expected behavior**

- minimum: Test should be rendered as FAIL
- ideal: Show the data table unrolled tests as single tests and show which ones failed.

**Screenshots**

<img width="1090" alt="grafik" src="https://user-images.githubusercontent.com/117198/206883119-59c83c9e-103e-4f29-b7c3-d516534c300c.png">

**Environment**

- OS: macOS Ventura 13.0.1
- VSCode version:  1.74.0
- Vitest version: 0.25.6
- Vitest plugin version: v0.2.34

**Additional context**

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
