### ISSUE TITLE
After canceling tests, the status bar icon still shows "Running tests...".

### ISSUE THREAD

**Issue by Asnow-c** [vitest-dev/vscode#109]
**Describe the bug**
When my tests got stuck in a wireless loop, I tried to abort the tests through the test panel, but the status bar still said "Running test..."

**To Reproduce**

1. Run tests through the Run Tests icon in the test panel or editor
2.  Click 'cancel Test Run' icon

**Expected behavior**
The status bar icon should stop rotating

**Screenshots**
1. Cancel a running test
![SCR-20221213-jh4](https://user-images.githubusercontent.com/73151139/208031193-72e99b47-3d73-4bb1-ba4c-81852ed976e6.png)

2.The status bar icon is still rotating
![SCR-20221213-jg0](https://user-images.githubusercontent.com/73151139/208031203-4c99fdb9-aae3-4c1f-a385-457965827701.png)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS
- VSCode version: 1.740
- Vitest version: 0.25.6
- Vitest plugin version: 0.2.34

**Additional context**

**Comment by branaway** [comment]
same here. it keeps spinning forever.

**Comment by frozar** [comment]
I'm experiencing the same with latest version of vitest (0.26.2) and the latest version of vitest-plugin (0.2.34).

**Comment by IGx89** [comment]
I've submitted #114 to fix this issue. The promise for the test run wasn't being resolved when canceled. Additionally, the vitest node process wasn't being terminated.
