### ISSUE TITLE
When the test throws an exception, the icon keeps loading

### ISSUE THREAD

**Issue by Asnow-c** [vitest-dev/vscode#120]
**Describe the bug**

When the test runs, the icon keeps rotating: 
```
import { test, expect } from "vitest";

test("test1", () => { // The test will not end
    throw "";
    expect(true).toBeTruthy();
});
```

This problem does not occur with vitest 0.26.3

**To Reproduce**

1. Click the Run button next to the test

**Expected behavior**

The plug-in should prompt an error

**Screenshots**

![image](https://user-images.githubusercontent.com/73151139/212476331-76e7ce18-f6f2-41a7-bc68-0833595177e4.png)

**Environment**

- OS: Windows 11
- VSCode version: 1.74.3
- Vitest version: 0.27.1
- Vitest plugin version: 0.2.36

**Comment by zxch3n** [comment]
Cannot reproduce it on my machine. Does it work now?

**Comment by olemarius** [comment]
Same here: 

![image](https://user-images.githubusercontent.com/184536/227738151-e7aa003b-6c6a-41e7-bd9d-2cc8f85d4025.png)

Also tried removing all the broken tests, still keeps spinning:
![image](https://user-images.githubusercontent.com/184536/227738500-ad66c89e-71b7-4c0f-a331-312f7843c55e.png)
