### ISSUE TITLE
Unable to cancel debug  when the test results do not match expectations

### ISSUE THREAD

**Issue by Asnow-c** [vitest-dev/vscode#121]
**Describe the bug**
```
import { test, expect } from "vitest";

test("test1", () => {
    expect(false).toBeTruthy();
});
```

**To Reproduce**
1:
![image](https://user-images.githubusercontent.com/73151139/212480926-beb2b4bb-6bae-447f-9709-a92a47f64b6c.png)
2: When debug console output test fails, click button:
![image](https://user-images.githubusercontent.com/73151139/212481312-9591f83a-74e0-462a-8e1c-8593bb41d7df.png)

**Expected behavior**
Exit debug

**Environment**

- OS: Windows 11
- VSCode version: 1.74.3
- Vitest version: 0.27.1
- Vitest plugin version: 0.2.36

**Comment by Mule52** [comment]
I am seeing the same issue. If a test fails, I cannot remove that debug dialog unless I restart VS Code.
