### ISSUE TITLE
If test failed, there no info why it happen

### ISSUE THREAD

**Issue by ayuka-bg** [vitest-dev/vscode#122]
**Describe the bug**
When i run only one test in sidebar, If test failed, there no info why it happen. Only message - "Test result not found".

**To Reproduce**
1. Run test in VIA buttons in VS Code (not CLI)
2. Wait
3. "Test result not found" message

**Expected behavior**
Info about why test failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/24483169/213446708-5df3d375-cfd7-4a11-acae-79d9eddb81f9.png)

**Environment**
-- MacBook Pro 16 (2019) MacOS Monterey,
-- VS Code 1.70.1
-- Vitest 0.26.3
-- Vitest extension 0.2.36

**Comment by jclaveau** [comment]
I have the same issue only on some tests with the default configuration and vitest working perfectly from the cli.

Do someone know if there is any way to debug/dump what's failing?

Also, on some tests runs, the process never ends, with the little loaders looping for ever.

**Comment by predam** [comment]
I am having the same problem.

**Comment by MilanKovacic** [comment]
New version of extension has been released on https://marketplace.visualstudio.com/items?itemName=vitest.explorer. Please try it out, and if the issue still persists, feel free to open a new one.
