### ISSUE TITLE
Support custom `dir` from vitest config

### ISSUE THREAD

**Issue by Exelord** [vitest-dev/vscode#123]
**Is your feature request related to a problem? Please describe.**
Im using vitest together with playwright and I keep both tests suites in different folders. I have used vitest config property `dir` to customize a base path where tests are located, however the vscode extension seams to not respect that.

**Describe the solution you'd like**
Respect config property.

**Describe alternatives you've considered**
Seams no other option.

**Comment by sandercoffee** [comment]
current extension doesn't work with turborepo :(

**Comment by Exelord** [comment]
I am not using turborepo :)

**Comment by zxch3n** [comment]
Duplicate of #101

**Comment by Exelord** [comment]
I don't thing this is related. I don't have a problem with running tests. Instead it's about vitest config that is not respected.

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
