### ISSUE TITLE
Only Show Vitest Run Options In Vitest Packages

### ISSUE THREAD

**Issue by RhysSullivan** [vitest-dev/vscode#126]
**Is your feature request related to a problem? Please describe.**
When I'm developing in a monorepo with both the Jest and Vitest VSCode extensions, I am presented with multiple options to run my tests from the context menu when I'd like to only see the option that is relevant for the file that I am developing in

**Describe the solution you'd like**
I'd like the Vitest extension to not appear in the context menu in packages where it is not active

**Describe alternatives you've considered**

**Additional context**

Current Behavior:
![image](https://user-images.githubusercontent.com/39114868/213945662-1f5d4884-4228-4ed6-88f8-5eab7b34d579.png)

Ideal Behavior:
![image](https://user-images.githubusercontent.com/39114868/213945685-95b0d27a-2736-41fd-aa87-8a09e25fb6f9.png)

Sample repostiory where this is occuring:

https://github.com/AnswerOverflow/AnswerOverflow

read-the-rules-consent.test.ts <- Uses Jest, has options to run via Jest and Vitest in the context menu when it should only be Jest

channel_settings.test.ts <- Uses Vitest, only option is to run via Vitest which makes me think the Jest VSCode extension is able to detect when to appear / not appear

https://github.com/jest-community/vscode-jest <- VSCode jest extension that may be a helpful reference

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
