### ISSUE TITLE
Missing test options in interface of plugin version 0.2.37

### ISSUE THREAD

**Issue by willem-kubusinfo** [vitest-dev/vscode#128]
After the upgrade to plugin version v0.2.37 the "Run test" and "Debug test" icons disappeared from the test explorer. They are also missing from the right click menu for tests. Reverting to v0.2.36 resolved the problem for now.

v0.2.37 (bug):
<img width="299" alt="image" src="https://user-images.githubusercontent.com/41572648/214808448-451df6b6-90ef-4a00-a09a-8f46c9075578.png">

v0.2.36 (expected):
<img width="233" alt="image" src="https://user-images.githubusercontent.com/41572648/214808182-41151192-93ef-45aa-bcc2-37abd0ac5114.png">

- OS: Windows 11
- VSCode version: 1.74.3
- Vitest version: v0.23.4
- Vitest plugin version: v0.2.37

**Comment by CharleeWa** [comment]
So do I.

**Comment by xplicitone** [comment]
Same, no Run Tests option at all. Also kept getting an error in VS Code: `Because Vitest version < 0.12.0, run/debug/watch tests are disabled in workspace`. Reverting Vitest back to v0.2.36 fixed it.

**Comment by zxch3n** [comment]
Does it work now on v0.2.38?

**Comment by CharleeWa** [comment]
@zxch3n It worked, thanks!
