### ISSUE TITLE
Does not work with HelloWorld.spec.ts after `npm init vue@latest`

### ISSUE THREAD

**Issue by cory-baker** [vitest-dev/vscode#129]
**Describe the bug**
test does not run. Play button results in infinite spinner

**To Reproduce**
-Creating new app with `npm init vue@latest`
-Install Vitest extension on vscode 
-Hit "play" button next to "HelloWorld.spec.ts"
-Extension will freeze and test will not run

**Expected behavior**
Test should turn green or red 

**Screenshots**
![image](https://user-images.githubusercontent.com/29523975/215922497-9d5de9ac-f48a-4dae-88e0-5398945a1f35.png)

**Environment**

error when running script

- OS: MacOS
- VSCode version: 1.74.3 
- Vitest version: "^0.25.6"
- Vitest plugin version: 0.2.37

**Additional context**

**Comment by cory-baker** [comment]
resolved by adding this to .vscode/settings.json

should maybe be added to docs

`"vitest.nodeEnv": {
    "PATH": "/usr/local/bin:/usr/bin:/bin"
  }`

**Comment by Zazcallabah** [comment]
I thought the point of an init script was that it should work out of the box, not "out of the box but also you need to read docs/google errors". I think you should reopen this issue until the problem is fixed.
