### ISSUE TITLE
Not able to get version on MacOS (0.2.37)

### ISSUE THREAD

**Issue by baivoom** [vitest-dev/vscode#131]
**Describe the bug**

This commit may fix version issue for Windows, however it could cause version checking issue on MacOS

https://github.com/vitest-dev/vscode/commit/f981f1c813c575470f5d5edd20ef61d6bc927d5e

0.2.36

![image](https://user-images.githubusercontent.com/26266290/216841273-3b9544bc-42d1-45a4-88cf-b37f4a1c91aa.png)

0.2.37

![image](https://user-images.githubusercontent.com/26266290/216841427-8ada992c-d4b6-4337-ab44-45851d1d24e2.png)

Env

MacOS 12.3

![image](https://user-images.githubusercontent.com/26266290/216841743-e2d754be-c178-4b73-ab1e-25cd9eee0bb7.png)

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Use Mac version of vscode, go to vscode extension install the latest 0.2.37
2. Write a test 
3. Reopen the workspace/folder
4. See the notification 
6. See error

**Expected behavior**

Should get the version instead of throwing an error

**Screenshots**

See the description

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: MacOS 12.3
- VSCode version:  see the screenshot 
- Vitest version: see the screenshot 
- Vitest plugin version:  see the screenshot 

**Additional context**

**Comment by zxch3n** [comment]
Is it fixed now on v0.2.38?

**Comment by baivoom** [comment]
It works perfectly 

![image](https://user-images.githubusercontent.com/26266290/217548212-8c22e35c-ea96-431a-b833-dfb7161c1d4c.png)

Thanks for the fix. 

@ngirardin @zxch3n

**Comment by zxch3n** [comment]
Nice

**Comment by ngirardin** [comment]
You're welcome @baivoom 🤗
