### ISSUE TITLE
Use runtime information to update the tests info

### ISSUE THREAD

**Issue by zxch3n** [vitest-dev/vscode#133]
This extension currently relies on the babel parser to calculate the positions of tests statically. So it doesn't support 

- test.each #7 #130
- Renamed `test` or `describe` #127

**Comment by Maxim-Mazurok** [comment]
I saw your PR about watch mode #33 where you used `vitest --api`, I thought it'd help with test list generation, doesn't it?

**Comment by lz2007** [comment]
when my projrect use pnpm , it no work, it is loading alway

**Comment by firatoezcan** [comment]
Btw, for everyone that reads this, I moved my tests out of my `*.spec.ts` files into `*.each.spec.ts` files and added rules so the extension doesn't run them but the CLI still does:

```
"vitest.exclude": ["**/*each.spec.{ts,tsx}", "**/node_modules/**", "**/dist/**", "**/cypress/**", "**/.{idea,git,cache,output,temp}/**"],
"vitest.include": ["**/*.spec.{ts,tsx}"]
```

This works like a charm

**Comment by ytw0728** [comment]
Hello! I appreciate your efforts.
could you let me know this issue's current status in the second one (renamed test or describe)?

is it dealing with now? and which version do you think it will be released?

**Comment by sheremet-va** [comment]
This is now supported in 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
