### ISSUE TITLE
After stopping watch mode, endless node.exe -> esbuild.exe root processes appear

### ISSUE THREAD

**Issue by varmiral** [vitest-dev/vscode#134]
**To Reproduce**
1. Start/stop watching with vscode status bar
2. Inspect process explorer

**Screenshots**
After several iterations:
![image](https://user-images.githubusercontent.com/70450385/218107538-55f02414-e970-4fa5-89d2-69c10b848778.png)

**Environment**
- OS: Windows 10
- VSCode version: 1.75.1
- Vitest version: 0.28.4
- Vitest plugin version: 0.2.39

**Additional context**
![image](https://user-images.githubusercontent.com/70450385/218104974-edb82233-441e-477d-93ad-23a48130cefb.png)

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
