### ISSUE TITLE
No test output

### ISSUE THREAD

**Issue by hallsbyra** [vitest-dev/vscode#137]
**Describe the bug**
I don't get any output stdout/stderr in the Test Output.

**To Reproduce**
1. Click on Show Output to bring up the Test Output terminal.
2. Run a test that uses console.error or console.log.
3. Test Output records only the following:

>The test run did not record any output.
>
> \> Test run finished at 3/1/2023, 3:03:43 PM <

**Expected behavior**
What's written to stdout/stderr should turn up in Test Output.

**Screenshots**

<img width="687" alt="image" src="https://user-images.githubusercontent.com/2835896/222164091-c9889793-048c-4c73-9bc6-2c9fbf487efe.png">

**Environment**

- OS: Win11
- VSCode version: 1.75.1
- Vitest version: vitest/0.29.2 win32-x64 node-v19.7.0
- Vitest plugin version: 0.2.39

**Comment by abulka** [comment]
Isn't being able to view console output like this an explicitly advertised feature of this extension?  There is even an animation screenshot of this feature working on its marketplace homepage labelled `Inspect console output`.

Strange it doesn't work in practice - perhaps something needs to be configured? I'm getting console output OK when I run vitest on the command line.

**Comment by davireis** [comment]
FWIW, by making stdout/stderr synchronous as described in https://github.com/nodejs/node/issues/6379#issuecomment-1064044886, I can get the output without the need for the `sleep`.

**Comment by brion-fuller** [comment]
I see a similar thing.
**Environment**

- OS: 13.4 (Apple M1 Max)
- VSCode version: 1.85.1
- Vitest version: vitest/1.2.0
- Vitest plugin version: 0.2.43

**Comment by AlonMiz** [comment]
same here. not outputs
![image](https://github.com/vitest-dev/vscode/assets/1812912/dca8cf82-3398-4802-b946-9738bef02753)

**Comment by AltarBeastiful** [comment]
Same results on a newly created project

OS: Windows 10
VSCode version: 1.82.2
Vitest version: vitest/1.2.2
Vitest plugin version: 0.2.43

**Comment by gautelo** [comment]
I'm having the same issue. Additionally, when a test fails the popup over the code is empty.

OS: Windows 11 Enterprise - 22631.3007
vitest: 1.2.2
vitest extension: 0.2.43
vite: 5.0.12
vscode: 1.86.0

**Comment by leonardomontes** [comment]
Same issue. Let me know if I can further assist.

OS: MacOS Sonoma 14.3
vitest: 1.2.0
vitest runner: 0.2.43
vscode: 1.86.0

**Comment by AlonMiz** [comment]
working thanks

**Comment by gautelo** [comment]
Can confirm. This and new vstest package solved the issues for me as well. Thanks!

Love to see the plugin under vstest name as well ❤️
