### ISSUE TITLE
vitest version not detected with nvm and pnpm

### ISSUE THREAD

**Issue by jonyo** [vitest-dev/vscode#138]
**Describe the bug**
It gives the error: 
```
[Extension Host] Error: Cannot get vitest version. Please open an issue at https://github.com/vitest-dev/vscode/issues and join the logs above.
```

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. On mac, be using a repo with vitest and playwright set up, and vitest already working on command line.
2. Be using nvm for node.
3. Try to install / enable the extension.

**Expected behavior**
The extension loads and lets you run tests in VSC instead of giving an error.

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

No info.txt generated.  Instead got this error:
```
╰─± node setup.mjs
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.08s.
Vitest settings updated
/bin/sh: /Applications/Visual: No such file or directory
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.6.0
```

Maybe because of the space in the path?

- OS: macOS
- VSCode version:  1.75.1 (Universal)
- Vitest version: vitest/0.12.10 darwin-x64 node-v19.6.0 (in this test repo
   - vitest/0.28.5 in my own repo I am trying to get the extension working
- Vitest plugin version: v0.2.39

**Additional context**

I noticed the setup script set the nodeEnv value in the settings. With it set the tests do work on the example repo (though the setup does not finish as mentioned above). We commit the settings file, and since the PATH is not the same on everyone's machine, setting the value in the project settings isn't really viable.

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
