### ISSUE TITLE
Vitest version = undefined

### ISSUE THREAD

**Issue by doei** [vitest-dev/vscode#142]
![image](https://user-images.githubusercontent.com/9954985/226620297-5a9e0520-da6b-468b-b74a-edbd6100a9d8.png)

In the screenshot above the green play arrow is not clickable, with the error log shown in the vitest output.
Seems to be related to #44 and #88, but it doesn't appear to be fixed for me.

**Environment**

- OS: macOS
- VSCode version: 1.76.2
- Vitest version: 0.29.3
- Vitest plugin version: 0.2.39

**Additional context**

I am running in a docker container, from the official node image `node:lts-alpine`
It works without issue when ran from the command line:
![image](https://user-images.githubusercontent.com/9954985/226623115-3b537273-3d75-47bc-898b-98b5d773f610.png)

**Comment by iGoodie** [comment]
I also have the same issue. Although I suspect a `path contains a space` error.
My project folder is located under some path like so: `E:/VS Code Workspace/MyProject`, which has space characters in it.
And Vitest logs those:
```
[INFO 2:46:46 AM] Trying to get vitest version from e:\VS Code\MyProject\node_modules\.bin\vitest.cmd -v...
[INFO 2:46:46 AM] Trying to get vitest version from E:\VS Code Workspace\Code.exe e:\VS Code\MyProject\node_modules\.bin\vitest.cmd...
[INFO 2:46:46 AM] Error: Cannot get vitest version. Please open an issue at https://github.com/vitest-dev/vscode/issues and join the logs above.
```

However, when I run the command in PowerShell I get this:
```
$ &"e:\VS Code\MyProject\node_modules\.bin\vitest.cmd" -v
> vitest/0.30.1 win32-x64 node-v18.15.0
```

I haven't checked how the code tries to extract Vitest version, but I suspect that

**Comment by doei** [comment]
Thanks for the investigation ! I hope this gets merged fast then.

**Comment by ilteoood** [comment]
With the latest version of the extension (0.2.40) I started to have the same problem.

Here are the logs:
```
[INFO 14:33:15] Trying to get vitest version from /Users/ilteoood/Documents/git/bmg/bv-be/node_modules/.bin/vitest -v...
[INFO 14:33:15] Command not found
[INFO 14:33:15] Trying to get vitest version from /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ilteoood/Documents/git/bmg/bv-be/node_modules/.bin/vitest -v...
[INFO 14:33:15] Command not found
[INFO 14:33:15] Error: Cannot get vitest version. Please open an issue at https://github.com/vitest-dev/vscode/issues and join the logs above.
[INFO 14:33:15] process.env.PATH = /Users/ilteoood/.nvm/versions/node/v18.12.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[INFO 14:33:15] vitest.nodeEnv = null
[Error 14:33:15] Error: Cannot get vitest version. Please open an issue at https://github.com/vitest-dev/vscode/issues and join the logs above.
[INFO 14:33:15] Vitest Workspace [bv-be]: Vitest version = undefined
[Error 14:33:15] Because Vitest version < 0.12.0 for every workspace folder, run/debug/watch tests from Vitest extension disabled.
```

But if I run the command on the terminal:
```
/Users/ilteoood/Documents/git/bmg/bv-be/node_modules/.bin/vitest -v
vitest/0.31.1 darwin-arm64 node-v18.12.1
```

**Comment by zxch3n** [comment]
Published another fix on 0.2.41 that should work on both mac and win

**Comment by ilteoood** [comment]
> Published another fix on 0.2.41 that should work on both mac and win

Yes, confirmed! Thank you so much!

**Comment by doei** [comment]
Still not working for me on 0.2.41

![image](https://github.com/vitest-dev/vscode/assets/9954985/7d2e793c-6c31-4002-8b07-71b29783db65)

My vitest version is 0.31.0

**Comment by whiterqbbit** [comment]
Still not working for me on Ubuntu 22.04

**Comment by moshikshechter** [comment]
Hi! I am also suffering from this. My env: WSL2 with Ubuntu, with the latest version (0.2.41)

**Comment by sjoerdvanBommel** [comment]
Same for me, doesn't seem to work with latest version (0.2.42). I created a similar (possibly duplicate) issue: #171. For me the play buttons become unclickable when watch mode is running (see mentioned issue).

**Comment by r1m** [comment]
In my case I feel this is because of the combinaison of a node version manager (no global node installed) and pnpm.
Because if I look at the logs
```
[INFO 1:57:22 PM] Trying to get vitest version from /home/me/projects/my-project/node_modules/.bin/vitest -v...
[INFO 1:57:23 PM] Trying to get vitest version from /home/me/.vscode-server/bin/fdb98833154679dbaa7af67a5a29fe19e55c2b73/node /home/me/projects/my-project/node_modules/.bin/vitest -v...
```
The first command runs well in a terminal because node is in my path. But probably fails because it is **not** in the extension process.env.PATH
The second one fails because `.bin/vitest` is a bash shim created by pnpm not a direct nodejs module.

**Comment by r1m** [comment]
If I add shims for my tools manager it works (rtx in my case): https://github.com/jdx/rtx#ide-integration
I should be similar with nvm and others
