### ISSUE TITLE
commandLine setting ignored

### ISSUE THREAD

**Issue by lowki** [vitest-dev/vscode#144]
`commandLine` setting seems to be ignored.
As I don't know how to see what command is actually used, I've specified a wrong one one purpose, but tests are still running.

```json
{
    "vitest.commandLine": "bad command"
}
```

<img width="611" alt="image" src="https://user-images.githubusercontent.com/1659775/227525838-1fa49906-5867-4068-96f3-ac56c0e8b932.png">

Running a fresh VSCode install on MacOS Ventura

**Comment by lowki** [comment]
Turns out the command setting is not ignored, I've managed to put logs in the extension itself.
If you run tests from test explorer, you should see the command actually ran in the Output tab.

**Comment by ButuzGOL** [comment]
seems like after restart vscode it gets this setting
