### ISSUE TITLE
tests spinning forever and output shows test not found

### ISSUE THREAD

**Issue by dev-seahouse** [vitest-dev/vscode#146]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

**Expected behavior**

**Screenshots**
<img width="824" alt="image" src="https://user-images.githubusercontent.com/4751342/228780529-65be2431-d333-40a7-92bc-db99eb820481.png">

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: [e.g. macOS] windows 10 wsl2
- VSCode version:  1.75.1
- Vitest version: 0.28.5
- Vitest plugin version: v0.2.39

**Additional context**
related to closed issues https://github.com/vitest-dev/vscode/issues/47 , https://github.com/vitest-dev/vscode/issues/8 and many others but issue still persists.

**Comment by dev-seahouse** [comment]
seems to be related to https://github.com/vitest-dev/vscode/issues/110

**Comment by nonameolsson** [comment]
I can confirm that I have the same problem.

**Comment by JoJk0** [comment]
And me too having the same problem

**Comment by whiterqbbit** [comment]
Having the same problem too, everything latest version on ubuntu 22.04

**Comment by danielwwc** [comment]
Having the same problem. 
- "vitest": "^0.33.0",
- "vite": "^4.4.6",
- "vitest-dev/vscode": "v0.2.42"
it was working on node 16 but not on node 18.
Tried changing the verbose and tried all vitest-cli commands and nothing works.

<img width="674" alt="image" src="https://github.com/vitest-dev/vscode/assets/12077820/46fb35d8-4353-4f33-adf1-ab46a8aa3a30">

**Comment by danielwwc** [comment]
Update to my previous comment ☝️ :
The test results is working for me. It was having issues with the merged config with `vite.config.ts`,

In my case the `https` and `basicSSL plugin` need to remove.

```javascript
import viteConfig from './vite.config';

const config = viteConfig();
delete config.server;
config.plugins = config.plugins.filter((plugin) => plugin?.name !== 'vite:basic-ssl');
```

The same issue appears for `create-vue` template. The extensions is not working when adding `{ server: https: true }`
<img width="738" alt="image" src="https://github.com/vitest-dev/vscode/assets/12077820/92a4779b-a914-4869-8e03-122f0c28b6d2">

**Comment by MilanKovacic** [comment]
Hi, we are tracking the issue related to basicSsl plugin in https://github.com/vitest-dev/vscode/issues/226.
