### ISSUE TITLE
ignores get .env.local variables

### ISSUE THREAD

**Issue by ButuzGOL** [vitest-dev/vscode#147]
when i do ```yarn test```
 i am getting **env variables** using 
 ```const env = loadEnv(mode, process.cwd(), '');```

 When i run with extension it ignores

**Comment by dcsan** [comment]
same #202

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.

`process.cwd()` would be equal to the file the config is in.
