### ISSUE TITLE
Running vitest from status bar changes workspace setting `"testing.automaticallyOpenPeekView": "never"`

### ISSUE THREAD

**Issue by sagarpanchal** [vitest-dev/vscode#148]
**Describe the bug**
it should not modify workspace settings

**To Reproduce**
click on vitest on statusbar

1. check workspace `settings.json`

**Expected behavior**
it should not modify workspace settings

**Comment by langaads** [comment]
Same behavior for me, it's annoying, i keep seeing people commiting this change by accident in our workspace settings.

**Comment by huwshimi** [comment]
I've created [a PR](https://github.com/vitest-dev/vscode/pull/188) so that settings.json is no longer modified, and users who wish to have the peek view in watch mode can set `"testing.automaticallyOpenPeekViewDuringAutoRun": true`.
