### ISSUE TITLE
Since vitest 0.30 : SyntaxError: Cannot use import statement outside a module when running tests

### ISSUE THREAD

**Issue by acmichaud** [vitest-dev/vscode#154]
**Describe the bug**
When I run ALL the tests using the vscode extension, I get this error 
![image](https://user-images.githubusercontent.com/84919242/235210425-96c564cb-089b-4c32-a633-3895969c9ea5.png)

```
/.../vitest.config.js:2

import { defineConfig } from 'vite'

^^^^^^

SyntaxError: Cannot use import statement outside a module
```

And the test just runs until I press stop. 
The thing is that the debug play button works fine ...
![image](https://user-images.githubusercontent.com/84919242/235211426-6de74b6f-8be0-4369-a00d-a5dc5df70295.png)

**To Reproduce**
Here is my configuration : 

vitest.config.js
```js
import { defineConfig } from 'vite'
// other imports

export default defineConfig({
//.......
})
```
**Environment**

- OS: Windows
- VSCode version: 1.77.3
- Vitest version: 0.30.1
- Vitest plugin version:  v0.2.39

**Comment by coderwei99** [comment]
I encountered this problem in the my monorepo project, I set type=module in package. json to solve my problem. I don't know if that's gonna solve your problem
```
{
  "type": "module",   //here
  "scripts": {
       // your code
  }
}
```

**Comment by acmichaud** [comment]
Hi there! This solved the error thx!... 

But now I get a new one :(

```
Test result not found. 
If you set `vitest.commandLine` please check: 
    Did you set `vitest.commandLine` to `run` mode? (This extension requires `watch` mode to get the results from Vitest api)
    Does it have the ability to append extra arguments? (For example it should be `yarn test --` rather than `yarn test`)
Are there tests with the same name?
Can you run vitest successfully on this file? Does it need custom option to run?
```

Again, the debug tests works fine and also the command line `vitest run` are working.

**Comment by coderwei99** [comment]
#47  
here

**Comment by kcaswick** [comment]
I encountered this error as well. Seems like if `npx vitest` can detect that it is an ESM without the type in package.json, so should this extension.

**Comment by acmichaud** [comment]
Here is the link to the solution : https://github.com/vitest-dev/vscode/issues/47#issuecomment-1612673645
It worked for me.
