### ISSUE TITLE
Test should NOT be launched in Source Control Tree View

### ISSUE THREAD

**Issue by Jason3S** [vitest-dev/vscode#156]
## **Describe the bug**
When trying to revert a change that happens to be on a "test" line, tests are started and cause problems. This can even pollute the screen with no way to get rid of the error message.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/3740137/236632103-08fd0e2e-7f64-40b0-b85d-da2d1a086b44.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/3740137/236632143-f86a8886-69bf-4055-b340-63e8f2c1a35c.png">

As a bonus, the error message is very annoying. The only way to make it go away is to quit VS Code. I think this is because the extension does not correctly support `.each` tests.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/3740137/236632359-17aa3b19-4560-4b2e-9c14-ab393d5a37f2.png">

## **To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Open a test file.
3. Add `.skip` after one of the tests: `test(...` => `test.skip(...`
4. Open Source Control View 
   <img width="57" alt="image" src="https://user-images.githubusercontent.com/3740137/236632807-f0d8e8c7-bf83-4dc7-bf68-d82aedb27acb.png">
1. Try to "Revert" the change using the `->` without running the test by just clicking on the arrow.
   <img width="384" alt="image" src="https://user-images.githubusercontent.com/3740137/236632103-08fd0e2e-7f64-40b0-b85d-da2d1a086b44.png">

**Expected behavior**
As a user, I do not want tests to run when I'm trying to revert code changes.

**Screenshots**
Added above.

## **Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- Version: 1.78.0 (Universal)
- Commit: 252e5463d60e63238250799aef7375787f68b4ee
- Date: 2023-05-03T20:11:00.813Z
- Electron: 22.4.8
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 22.4.0
- Sandboxed: Yes
- Vitest version: vitest/0.29.8 darwin-x64 node-v16.18.1
- Vitest plugin version: v0.2.39

**Additional context**

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
