### ISSUE TITLE
Feature Request: Allow configuration of `skipFiles`

### ISSUE THREAD

**Issue by justrhysism** [vitest-dev/vscode#16]
There are times when there's an issue within a `node_module` package—or indeed we're trying to gain a better understanding of what a package is doing internally—where it would be useful to easily step through the code.

Unfortunately as `skipFiles` is hardcoded, it's impossible to enable this.

Would be great if we could override the default `skipFiles` setting.

**Comment by zxch3n** [comment]
You can override this by `vitest.exclude` setting
