### ISSUE TITLE
"Test result not found" if i import something in import,  such as  {myadd} from "@apiAdd/myadd"

### ISSUE THREAD

**Issue by zp7541** [vitest-dev/vscode#164]
**Describe the bug**
when is use import { myadd } from "@/apiAdd/myadd", it report "Test result not found"
if i import { myadd } from "./myadd/myadd", it works OK

**To Reproduce**

1. git clone https://github.com/zxch3n/vitest-ext-basic-example.git && cd vitest-ext-basic-example
2. mkdir -p myadd && touch myadd/myadd.ts 
3. cat myadd/myadd.ts 
```
export const myadd = (a: number, b: number): number => {
  return a + b;
};
```
4. cat add.test.ts
```
import { describe, it, expect } from "vitest";
import { myadd } from "@apiAdd/myadd";

describe("add", async () => {
  it("1 + 1", async () => {
    let c = myadd(1, 1);
    expect(c).toBe(3);
  });
});
```
5. cat tsconfig.json
```
// i add the path
    "paths": {
      "@apiAdd/*": [
        "./myadd/*"
      ]
    }, 
```
- OS: ubuntu18.04
- VSCode version: 1.79.2
- Vitest version: 0.12.6
- Vitest plugin version: 0.24.1

**Additional context**
if i want to use @path1/path2, what should i do

**Comment by sheremet-va** [comment]
This is not the problem with the extension. Vitest doesn't use `paths` form tsconfig, you need to add [an alias](https://vitest.dev/config/#alias) or use [vite-tsconfig-paths](https://www.npmjs.com/package/vite-tsconfig-paths) plugin.
