### ISSUE TITLE
Debug Test mode does not start

### ISSUE THREAD

**Issue by nicolanilomartinoph** [vitest-dev/vscode#165]
**Describe the bug**
Starting the Debug Test mode does not stop at my breakpoint but gives the loading spinning icon then it stops or it spins forever. I am using Typescript. Running the test using my script "npm test" works though. 

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

created a test file:
```
import { afterEach, beforeEach, describe, expect, it, vi, test } from 'vitest'


describe("testing", ()=>{
    it("runs", ()=>{
        expect(1+1).toBe(2)
    })
})
```

2. Go to Vitest Extension and click on "Debug Test" or Right-click the breakpoint Play Test icon, click "Debug Test".
3. The loading icon spins and stops or it spins forever.

**Expected behavior**
I expect the test to stop at the breakpoint.

**Screenshots**
![image](https://github.com/vitest-dev/vscode/assets/60249499/a11b5a8e-2399-48dc-8a78-0f1392d79040)

![image](https://github.com/vitest-dev/vscode/assets/60249499/951b0050-8ef5-4f67-8c23-fdcc9b074180)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: Win10
- VSCode version: 1.79.2
- Vitest version:  8.11.0
- Vitest plugin version: latest

**Additional context**
[New folder (2).zip](https://github.com/vitest-dev/vscode/files/11811114/New.folder.2.zip)

The zip file contains my package.json, test file, tsconfig.json

**Comment by GorenDaniel** [comment]
I have the same issue. It appears to be running vitest directly instead of using npm as specified in the vitest.commadLine argument. This is the logged command:
```
/Users/myuser/.nvm/versions/node/v18.16.0/bin/node ./node_modules/vitest/vitest.mjs run test -- /Users/myuser/Documents/unit-tester/test/e2e/apg/tests/TESTNAME.test.ts -t TEST DESCRIPTION --api.port 53927 --api.host 127.0.0.1
```

**Comment by MilanKovacic** [comment]
New version of extension has been released on https://marketplace.visualstudio.com/items?itemName=vitest.explorer. Please try it out, and if the issue still persists, feel free to open a new one.

**Comment by GorenDaniel** [comment]
still reproduces, opened a [new issue](https://github.com/vitest-dev/vscode/issues/266).
