### ISSUE TITLE
How can I use it in monorepo?

### ISSUE THREAD

**Issue by lz2007** [vitest-dev/vscode#166]
when my project is pnpm workspace,It not work.
```[tasklist]
### Tasks
```

**Comment by dementors-magnus** [comment]
You need to configure a [vitest workspace](https://vitest.dev/guide/workspace.html) and install vitest in the workspace root.

[This example](https://github.com/vitest-dev/vscode/issues/110#issuecomment-1588760688) by @koistya was really helpful

**Comment by uk-taniyama** [comment]
Define a workspace like this and test it.

<root>/.vscode/settings.json
```
    "vitest.commandLine": "npx vitest run",
```

<root>/vitest.workspace.ts
```
import { dirname } from 'node:path';
import { globSync } from 'glob';

const workspaces = globSync('packages/*/vite.config.ts')
  .map((name) => ({
    extends: name,
    root: dirname(name),
  }));
export default workspaces;
```

**Comment by ffMathy** [comment]
This has improved greatly in #231, and I think it is good enough to close now. Let me know if you disagree.
