### ISSUE TITLE
Any chance of support for in-source testing

### ISSUE THREAD

**Issue by Aaron-Pool** [vitest-dev/vscode#17]
I noticed the extension doesn't pick up on [in-source tests](https://vitest.dev/guide/features.html#in-source-testing). Any chance this feature will be supported in the future. I might be willing to contribute to a PR if I new it wouldn't sit dead in the PR board indefinitely.

**Comment by watonyweng** [comment]
Hi @zxch3n, if we want to support  [In-source Testing](https://vitest.dev/guide/in-source.html) in VSCode, we should add options to configure `includeSource` and dedect some files when there is a `if (import.meta.vitest){ } ` block in source code.

**Comment by szulcus** [comment]
What should I do to make the [plugin ](https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer) for VS Code work?
![image](https://user-images.githubusercontent.com/48328739/214594324-1707cefb-ce23-45aa-aedc-da7d81aa7ee4.png)

**Comment by nicolasreszka** [comment]
Hello, did you find a solution ?
