### ISSUE TITLE
Watch mode skips all tests in a clean SvelteKit project

### ISSUE THREAD

**Issue by sjoerdvanBommel** [vitest-dev/vscode#171]
**Describe the bug**
The VSCode Vitest plugin fails to execute any unit tests when running in watch mode (for example in a clean SvelteKit project).

**To Reproduce**

1. Create a clean TypeScript skeleton SvelteKit project with all options included: `npm create svelte@latest test-app`
2. `cd test-app`
3. `npm i`
4. (Optional) Run the tests with the default runner. This works as expected
![image](https://github.com/vitest-dev/vscode/assets/25690040/b8736a7c-9b1a-4709-84c7-7e241a440539)
5. Run the tests using watch mode
![image](https://github.com/vitest-dev/vscode/assets/25690040/f830e519-bbd1-4800-8218-e9169fe891d7)
6. All tests are skipped for some reason. At the top and bottom, it mentions "0/0 tests passed (0.00%)" and "0/0 passed (0%, all skipped)"
![image](https://github.com/vitest-dev/vscode/assets/25690040/b76acea9-5557-4ae1-b055-2a65f24cf088)

**Expected behavior**
Similar behavior to when I run the tests without watch mode, but instead affected tests should be re-run.

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: Windows 11 (OS build 22621.1848)
- VSCode version: 1.80.0
- Vitest version: ^0.32.2
- Vitest plugin version: v0.2.42

Let me know if anyone is able to reproduce this behavior. Thanks in advance! :)

**Comment by sjoerdvanBommel** [comment]
Two more points:

- I disabled all other VSCode extensions
- Once watch mode is running (it does run, it just skips all tests), starting any of the other tests does not trigger anything. You have to manually stop watch mode before you can run any tests via the plugin. You can do this by clicking the button below
![image](https://github.com/vitest-dev/vscode/assets/25690040/3b7a32d0-2b0d-4c37-a201-234d01612286)

**Comment by sjoerdvanBommel** [comment]
Couldn't find a related issue before, but found one now: #44 
It seems to be broken since vitest@0.28.5. The tests run as expected until vitest@0.28.4

**Comment by mcavigelli** [comment]
> Let me know if anyone is able to reproduce this behavior. Thanks in advance! :)

We are using vitest plugin 0.2.42, vitest 0.33.0, vite 4.4.3 and VSCode 1.80.0 on windows.
We have the same behaviour. It can easily be reproduced by setting up a project as in the vitest repository in the folder https://github.com/vitest-dev/vitest/tree/main/examples/basic.

**Comment by callmeberzerker** [comment]
I have the same issue on Windows 11.

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
