### ISSUE TITLE
Test runs through extension should run the provided test file only irrespective of the "test.include" property in config file.

### ISSUE THREAD

**Issue by riuandg5** [vitest-dev/vscode#176]
**Description**

Test runs through vitest extension is taking vitest configuration in consideration which throws error when running tests outside the filter provided by `test.include` property in the config file.

**Steps to Reproduce**

-   Directory structure

    ```
    .
    |__ .vscode
    |   |__ settings.json
    |__ src
    |   |__ inside.test.ts
    |__ outside.test.ts
    |__ vitest.config.ts
    ```
    Obviously `package.json` is there with `vitest` installed.

-   `settings.json`

    ```json
    {
        "vitest.enable": true,
        "vitest.commandLine": "npx vitest"
    }
    ```

-   `vitest.config.ts`

    ```ts
    import { defineConfig } from "vitest/config";

    export default defineConfig({
        test: {
            include: ["src/**/*.test.ts"], // default: ['**/*.{test,spec}.?(c|m)[jt]s?(x)']
        },
    });
    ```

-   Run `npx vitest`

    -   **Expected behavior**: Should run tests inside `src` directory only that is `inside.test.ts` only as it is mentioned in the `test.include` property in the config file.
    -   **Error**: No error.

-   Use **vitest extension** to run:

    -   `inside.test.ts`

        -   **Expected behavior**: Should run the `inside.test.ts`.
        -   **Error**: No Error.

    -   `outside.test.ts`

        -   **Expected behavior**: Should run the `outside.test.ts`.
        -   **Error**:

            ```Test result not found.
            If you set`vitest.commandLine`please check:
                Did you set`vitest.commandLine`to`run`mode? (This extension requires`watch`mode to get the results from Vitest api)
                Does it have the ability to append extra arguments? (For example it should be`yarn test --`rather than`yarn test`)
            Are there tests with the same name?
            Can you run vitest successfully on this file? Does it need custom option to run?

                    Vitest output:

                    DEV  v0.34.1 absolute/path/to/project/
                        API started at http://127.0.0.1:49892

                    ↓ src/inside.test.ts  (1 test | 1 skipped)
            ```

**More info**

-   Removing `test.include` property from the config file does not throw the error but then `npx vitest` also runs `outside.test.ts`.
-   Test runs through extension should run the provided test file irrespective of the `test.include` property filter.

**Environment**

-   OS: Microsoft Windows 10.0.19045 Build 19045
-   VSCode version: 1.81.0 (user setup)
-   Vitest version: 0.34.1
-   Vitest plugin version: 0.2.42

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.

**Comment by samducker** [comment]
Hi so I had this error intermittenantly @sheremet-va 

However I've switched to the pre-release version as per your advice, and now I get an error related to using my enviroment variables (I'm using Next.js 14 also) this error didn't previously exist just the one detailed in this thread did.

My new error:

Error: Missing API key. Pass it to the consutrctor `new Resend("re_123")`

```
import { beforeEach, expect, test } from "vitest";
import { loadEnvConfig } from "@next/env";
import { Resend } from "resend";

beforeEach(async () => {
  loadEnvConfig(process.cwd());
});

test("send survey started / payment confirmed email", async () => {
  const resend = new Resend(process.env.RESEND_API_KEY);
  const generateId = () => Math.random().toString(36).substring(7);
  const fakeSurveyId = generateId();
  const fakePaymentIntent = "pi_" + generateId();

  const { data, error } = await resend.emails.send({
    from: "Some company <support@mycompany.com>",
    to: "sam@mycompany.com",
    subject: "Your survey is live!",
    react: PaidSurveyLive({
      survey: {
        audience: "uk",
        question:
          "How likely are people to support a coffee brand that is environmentally friendly (test)",
        size: 1,
        id: fakeSurveyId,
      },
      paymentDetails: {
        date: new Date().toDateString(),
        discount: 0,
        total: 7900,
        paymentIntentId: fakePaymentIntent,
        paymentMethod: {
          type: "other",
          last4: "4242",
        },
        subtotal: 7900,
        tax: 0,
      },
      enviroment: process.env.NEXT_PUBLIC_ENVIROMENT === "production" ? "production" : "staging",
      previewText: "Your survey is live! Click the button below to view your survey results.",
    }),
  });

  expect(data).toBeDefined();
  expect(error).toBeNull();
});
```

**Comment by sheremet-va** [comment]
Please, create a new issue following the issue template.
