### ISSUE TITLE
How do I use this after installing it?

### ISSUE THREAD

**Issue by theronic** [vitest-dev/vscode#180]
What do I do next? I can run `pnpm run vitest` in terminal and it works, but there is no documentation on how to get this after installing it.

**Comment by ffMathy** [comment]
What is not working for you? When you go the test explorer UI, what do you see?

**Comment by wickedw** [comment]
Hi, I have just installed it, just feeding back, might help the docs, might not.

I get nothing in my test explorer.

 I am new to node dev, so bear with me, so not sure if classes as mono repo, it has a seperate npm / project structure in each folder.

I have /api/ with a vitest.config.ts and can run all my tests fine (they are in api/tests/vitest/*.test.*) from the command line with vitest.
I have /web/ with other code etc 

 I see the link to the a workspace setup at the bottom of the docs, but not sure if I need to work with that?

I use httpYac in the same /api directory and that shows tests no issue in the explorer.

**Comment by WesleyKapow** [comment]
I've been hitting this to ever since I moved away from the deprecated extension. No tests found. Vitest is working though as I can run `npx vitest watch` just fine. I'm working with a monorepo and I tried setting up a workspace file but that didn't seem to help.

![Screenshot 2024-03-08 at 12 40 04 PM](https://github.com/vitest-dev/vscode/assets/1568246/7d38cb22-e7fc-4fbd-8dec-d2f1b0ac12d0)

**Comment by 3ddbz** [comment]
我遇到了同样的问题，vscode 的日志是这样的：
![屏幕截图 2024-03-15 144032](https://github.com/vitest-dev/vscode/assets/9635160/af8ac7a4-b89b-4060-83fe-f326dda3d77b)
我在package.json 中增加了一行"vitest":"vitest" 就可以显示了：
`{
    //...
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "test": "vitest"
    }
    //...
}`
改为
`{
    //...
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "test": "vitest",
        "vitest":"vitest"
    }
    //...
}`

**Comment by MilanKovacic** [comment]
Usage section has been added to the readme. Feedback is welcome.
