### ISSUE TITLE
Tests not work with create-electron-vite app running from side panel or inline

### ISSUE THREAD

**Issue by MiniSuperDev** [vitest-dev/vscode#181]
The tests work in the cli.

**Describe the bug**

When try to run a test from the side panel or inline(click en the line of the test) not work.

The app was creating using `npm create vite@latest` https://electron-vite.github.io/guide/getting-started.html#scaffolding-your-first-vite-project

## Case 1: With the normal content of my app

Clone the following repository, and check this test
https://github.com/MiniSuperDev/electron-vite-vitest-bug-4159/blob/21f00245d4aad303693e9f023df0faa1ade73fc4/src/sum.test.ts#L4

It keep loading for ever, so I need to restart vs code, and show this errors:
![image](https://github.com/vitest-dev/vscode/assets/105388540/6995d7f1-e690-4023-8d6c-1c2f8b69d28a)

<details>
<summary>Output</summary>

```sh
 DEV  v0.34.5 C:/electron-vite-vitest-bug-4159

      API started at http://127.0.0.1:52113



vite v4.4.9 building for test...



watching for file changes...

vite v4.4.9 building for test...



watching for file changes...



build started...



build started...

transforming...

✓ 1 modules transformed.

transforming...

✓ 1 modules transformed.

rendering chunks...

rendering chunks...

computing gzip size...

computing gzip size...

dist-electron/preload.js  2.70 kB │ gzip: 1.10 kB

built in 229ms.

dist-electron/main.js  1.23 kB │ gzip: 0.58 kB

built in 231ms.
C:\electron-vite-vitest-bug-4159\dist-electron\main.js:5

process.env.VITE_PUBLIC = electron.app.isPackaged ? process.env.DIST : path.join(process.env.DIST, "../public");

                                       ^



TypeError: Cannot read properties of undefined (reading 'isPackaged')

    at Object.<anonymous> (C:\electron-vite-vitest-bug-4159\dist-electron\main.js:5:40)

    at Module._compile (node:internal/modules/cjs/loader:1271:14)

    at Object..js (node:internal/modules/cjs/loader:1326:10)

    at Module.load (node:internal/modules/cjs/loader:1126:32)

    at node:internal/modules/cjs/loader:967:12

    at Function._load (node:electron/js2c/asar_bundle:2:13377)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:96:12)

    at node:internal/main/run_main_module:23:47



Node.js v18.16.1
```

</details>

## Case 2: The  previous app, but I clean the main process of my app (nothing desired, but it was to see what more errors came out), 

Clone the following repository, and check this test

https://github.com/MiniSuperDev/electron-vite-vitest-bug-4159/blob/4acbba375b32f1b236adfb8a06196d2a36f54476/src/sum.test.ts#L4

![image](https://github.com/vitest-dev/vscode/assets/105388540/21183454-db99-4471-b8e9-da6152691ffc)

<details>
<summary>Output</summary>

```sh
Test result not found. 
If you set `vitest.commandLine` please check: 
    Did you set `vitest.commandLine` to `run` mode? (This extension requires `watch` mode to get the results from Vitest api)
    Does it have the ability to append extra arguments? (For example it should be `yarn test --` rather than `yarn test`)
Are there tests with the same name?
Can you run vitest successfully on this file? Does it need custom option to run?


Vitest output:

 DEV  v0.34.5 C:/electron-vite-vitest-bug-4159
      API started at http://127.0.0.1:53143

vite v4.4.9 building for test...

watching for file changes...
vite v4.4.9 building for test...

watching for file changes...

build started...

build started...
transforming...
✓ 1 modules transformed.
transforming...
✓ 1 modules transformed.
Generated an empty chunk: "main".
rendering chunks...
rendering chunks...
computing gzip size...
computing gzip size...
dist-electron/preload.js  2.70 kB │ gzip: 1.10 kB
built in 197ms.
dist-electron/main.js  0.01 kB │ gzip: 0.03 kB
built in 198ms.
```

</details>

**Expected behavior**
Run the test, like always

**Environment**

- OS: Windows
- VSCode version: 1.82.2
- Vitest version: ^0.34.5
- Vitest plugin version: v0.0.4

___

Thanks

**Comment by MiniSuperDev** [comment]
Maybe is related with this https://github.com/vitest-dev/vitest/issues/4159

**Comment by sheremet-va** [comment]
I don't think this is an issue with the extension. If this doesn't work with regular Vitest CLI, it won't work here. If it does work, then the extension should now also correctly run it in pre-release 0.5.0 and higher.
