### ISSUE TITLE
Duplicate test execution with monorepo/workspace setup

### ISSUE THREAD

**Issue by jzillmann** [vitest-dev/vscode#183]
**Describe the bug**
Using VSCodes `xxx.code-workspace` file and setting the ROOT folder up as well, leads to vitest running the tests twice.
```
[INFO 2:51:23 PM] Tests run start
[INFO 2:51:23 PM] [Workspace "ROOT] Run tests from workspace
[INFO 2:51:23 PM] [Execute Vitest] /myproject/node_modules/.bin/vitest /myproject/frontend/src/editor/complete4.test.ts -t options default functions
[INFO 2:51:23 PM] [Workspace "frontend] Run tests from workspace
[INFO 2:51:23 PM] [Execute Vitest] /myproject/node_modules/.bin/vitest /myproject/frontend/src/editor/complete4.test.ts -t options default functions
[INFO 2:51:23 PM] Start api process at port 61934
[INFO 2:51:23 PM] [RUN] /myproject/node_modules/.bin/vitest /myproject/frontend/src/editor/complete4.test.ts -t options default functions
[INFO 2:51:23 PM] [RUN.cwd] /myproject
[INFO 2:51:23 PM] Start api process at port 61935
[INFO 2:51:23 PM] [RUN] /myproject/node_modules/.bin/vitest /myproject/frontend/src/editor/complete4.test.ts -t options default functions
[INFO 2:51:23 PM] [RUN.cwd] /myproject/frontend
```

With this `.code-workspace` it runs the tests twice as shown above:
```
{
  "folders": [
    {
      "name": "ROOT",
      "path": "../"
    },
    {
      "name": "backend",
      "path": "../backend"
    },
    {
      "name": "frontend",
      "path": "../frontend"
    }
  ],
  "settings": {}
}
```

If I remove the ROOT folder the tests are only executed once.

**To Reproduce**

See setup above. Create a (npm) monorepo with vscode workspaces setup while including the ROOT folder as well.
Use the VSCode extension to run in test in a submodule.

**Expected behavior**
Shouldn't run the tests two times.

**Screenshots**
n/a

**Environment**

- OS: macOS
- VSCode version: 1.82.2
- Vitest version: 0.34.4
- Vitest plugin version: v0.2.42

**Additional notes**
As a side effect it seems to produce https://github.com/vitest-dev/vscode/issues/47 sporadically.

**Comment by marviobezerra** [comment]
I'm facing the same issue.

**Comment by ffMathy** [comment]
This should be greatly improved with #241, #232 and #231. I no longer get these issues.

**Comment by ffMathy** [comment]
Let's re-open this if it re-occurs for someone.
