### ISSUE TITLE
Support Custom Launch Configurations

### ISSUE THREAD

**Issue by JustinGrote** [vitest-dev/vscode#185]
**Is your feature request related to a problem? Please describe.**
I am authoring a cloudflare worker with an end-to-end test that starts `workerd` on a custom inspect port. When clicking the "debug" button, vitest uses its own custom debug launch config and I have no way to set up to attach to the `workerd` instance in order to debug internals.

**Describe the solution you'd like**
Provide a configuration option to supply a custom debug launch config, similar to the `Mocha Test Explorer`. vitest would then append its -t, --api-port, and --api-host to the args of that launch config.

Alternatively, provide an additional attach port setting in the config that will launch a child attach debug config on the specified port.

I would be willing to attempt a PR if there is interest, I wrote my own Test Extension for PowerShell Pester and am familiar with the internals.

**Comment by sheremet-va** [comment]
In the new extension, we attach to the process that runs Vitest instead of starting a new process. Do you think your proposal could still work with that approach?
