### ISSUE TITLE
Bad HTML tree shown in error messages

### ISSUE THREAD

**Issue by maasha** [vitest-dev/vscode#191]
On a failing test I see something like this in vscode:

<img width="529" alt="image" src="https://github.com/vitest-dev/vscode/assets/1158057/d3bd1c8f-3ec7-4854-b770-b9abe62e0e79">

I was not expecting all the `[`, `[` and `mXX`. How to get normal HTML?

**Comment by sheremet-va** [comment]
Maybe we should remove ANSI colors from the output.

**Comment by maasha** [comment]
So those are ansi-color codes? I have not used those for years. Anyways, do add some configuration option to remove if that is the case
!

**Comment by sheremet-va** [comment]
This should be fixed in 0.5.4 when it comes out.

**Comment by maasha** [comment]
This works fine now!
