### ISSUE TITLE
Vitest testing BAR is out of sync with tests in test files. 

### ISSUE THREAD

**Issue by louiss0** [vitest-dev/vscode#195]
**Describe the bug**

I was using vitest and noticed that the show testing UI is different than the results in the terminal.
In the terminal all my tests pass but in the Testing UI my tests are not finished. 

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/louiss0/cn-efs):

1. Activate Watch Mode
2. Then use the Vs Code command line to Click on View: Show Testing. 
3. Look at the toolbar 

**Expected behavior**
I expected the Testing Bar to show the same results as my tests 

**Screenshots**
![Screenshot 2023-11-05 133440](https://github.com/vitest-dev/vscode/assets/29028601/88b7d6de-f570-4505-91cd-d338471d3a21)

![Screenshot 2023-11-05 133504](https://github.com/vitest-dev/vscode/assets/29028601/b4956c34-eef5-43c0-962f-d5ae5189c165)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- VSCode version: 1.84.0
- Vitest version: 0.34.6
- Vitest plugin version: 0.2.43

**Additional context**

**Comment by sheremet-va** [comment]
In 0.5.0 we removed the bar altogether.
