### ISSUE TITLE
Vitest extension completely non functional on mac

### ISSUE THREAD

**Issue by benwainwrightawaze** [vitest-dev/vscode#196]
**Describe the bug**
Vitest completely fails to work on any of my vitest repos

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/benwainwright/vitest-vscode-issue-repro):

1. Open Vscode
2. Install Vitest extension
3. Go to 'testing' sidebar

**Expected behavior**
I see tests that I can execute

**Actual behavior**
I see 'install additional test extensions', and no tests.

Note, the vitest output window appears to be showing websocket connections dropping:

```
[INFO 17:42:27] Trying to get vitest version from /Users/ben.wainwright/personal-repos/vitest-basic/node_modules/.bin/vitest -v...
[INFO 17:42:28] vitest/0.34.6 darwin-arm64 node-v20.6.0

[INFO 17:42:28] Vitest Workspace [vitest-basic]: Vitest version = 0.34.6
[INFO 17:42:28] WS Close
[INFO 17:42:28] RECONNECT
[INFO 17:42:28] WS Close
[INFO 17:42:29] RECONNECT
[INFO 17:42:29] WS Close
[INFO 17:42:29] RECONNECT
[INFO 17:42:29] WS Close
[INFO 17:42:30] RECONNECT
[INFO 17:42:30] WS Close
[INFO 17:42:30] RECONNECT
[INFO 17:42:30] WS Close
[INFO 17:42:31] RECONNECT
[INFO 17:42:31] WS Close
[INFO 17:42:31] RECONNECT
[INFO 17:42:31] WS Close
[INFO 17:42:32] RECONNECT
[INFO 17:42:32] WS Close
[INFO 17:42:32] RECONNECT
[INFO 17:42:32] WS Close
[INFO 17:42:33] RECONNECT
[INFO 17:42:33] WS Close
[INFO 17:42:33] RECONNECT
[INFO 17:42:33] WS Close
[INFO 17:42:34] RECONNECT
[INFO 17:42:34] WS Close
[INFO 17:42:34] RECONNECT
[INFO 17:42:34] WS Close
[INFO 17:42:35] RECONNECT
[INFO 17:42:35] WS Close
[INFO 17:42:35] RECONNECT
[INFO 17:42:35] WS Close
[INFO 17:42:36] RECONNECT
[INFO 17:42:36] WS Close
[INFO 17:42:36] RECONNECT
[INFO 17:42:36] WS Close
[INFO 17:42:37] RECONNECT
[INFO 17:42:37] WS Close
[INFO 17:42:38] RECONNECT
[INFO 17:42:38] WS Close
```

**Screenshots**
![image](https://github.com/vitest-dev/vscode/assets/144028652/768031f4-9a95-4152-a1d2-6f5129e17138)

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: MacOS
- VSCode version: 1.84.1
- Vitest version: 0.34.6
- Vitest plugin version: 0.2.43

**Additional context**

**Comment by teobmg** [comment]
Same behaviour here

**Comment by teobmg** [comment]
It seems to be related with node 20. Rolling back to node 18.16.0 works fine.

**Comment by sbolz** [comment]
same behavior here, but on Windows with WSL2 (ubuntu). The extension is installed on the remote host.

```
[INFO 1:02:36 PM] Trying to get vitest version from /home/[...]/node_modules/.bin/vitest -v...
[INFO 1:02:37 PM] vitest/0.34.6 linux-x64 node-v18.16.1

[INFO 1:02:37 PM] Vitest Workspace [energycity]: Vitest version = 0.34.6
[INFO 1:02:37 PM] WS Close
[INFO 1:02:37 PM] RECONNECT
[INFO 1:02:37 PM] WS Close
[INFO 1:02:38 PM] RECONNECT
[INFO 1:02:38 PM] WS Close
[INFO 1:02:38 PM] RECONNECT
[INFO 1:02:38 PM] WS Close
[INFO 1:02:39 PM] RECONNECT
[INFO 1:02:39 PM] WS Close
[INFO 1:02:39 PM] RECONNECT
[INFO 1:02:39 PM] WS Close
[INFO 1:02:40 PM] RECONNECT
[INFO 1:02:40 PM] WS Close
[INFO 1:02:40 PM] RECONNECT
[INFO 1:02:40 PM] WS Close
[INFO 1:02:41 PM] RECONNECT
[INFO 1:02:41 PM] WS Close
[INFO 1:02:41 PM] RECONNECT
[INFO 1:02:41 PM] WS Close
[INFO 1:02:42 PM] RECONNECT
[INFO 1:02:42 PM] WS Close
[INFO 1:02:42 PM] RECONNECT
[INFO 1:02:42 PM] WS Close
[INFO 1:02:43 PM] RECONNECT
[INFO 1:02:43 PM] WS Close
[INFO 1:02:43 PM] RECONNECT
[INFO 1:02:43 PM] WS Close
[INFO 1:02:44 PM] RECONNECT
[INFO 1:02:44 PM] WS Close
[INFO 1:02:44 PM] RECONNECT
[INFO 1:02:44 PM] WS Close
[INFO 1:02:45 PM] RECONNECT
[INFO 1:02:45 PM] WS Close
[INFO 1:02:45 PM] RECONNECT
[INFO 1:02:45 PM] WS Close
[INFO 1:02:46 PM] RECONNECT
[INFO 1:02:46 PM] WS Close
[INFO 1:02:46 PM] RECONNECT
[INFO 1:02:46 PM] WS Close
```
Not sure if this gives any clue:
![image](https://github.com/vitest-dev/vscode/assets/2151660/300c5b0f-b884-490e-85cc-6538cbcd14b1)
The number behind `--api.port` doesn't match the `Port` number from the table.

**Comment by benwainwright** [comment]
> It seems to be related with node 20. Rolling back to node 18.16.0 works fine.

This makes no difference for me

**Comment by santi020k** [comment]
> It seems to be related with node 20. Rolling back to node 18.16.0 works fine.

I had node 20 and making the change to this specific version worked for me, Thanks <3

**Comment by nwidynski** [comment]
Downgrading the plugin version to v0.2.42 is what did the trick for me. 

v0.2.43 breaks the logging for some reason that needs to be investigated further. v0.2.42 logs an error in one of the vite.config.ts of my monorepo. After fixing this error, v0.2.43 also works.

**Comment by JCherryhomes** [comment]
downgrading to v0.2.42 worked for me as well

**Comment by leonardo-ornelas** [comment]
downgrading to v0.2.42 also worked for me

**Comment by ffMathy** [comment]
Do you happen to use `using` keywords in your tests or your code?

There was a bug regarding this that was now solved, which would lead to this exact error: #232

**Comment by ffMathy** [comment]
Have you noticed we moved the extension to a new download link, and the existing one has been deprecated? The new version has a lot of bug-fixes. Does this work for any of you?

**Comment by MilanKovacic** [comment]
There have been a lot of changes in the extension since this issue was opened. Please try to install the latest version, and open new issues for specific problems.
@goibon This issue is tracked in https://github.com/vitest-dev/vscode/issues/226
