### ISSUE TITLE
Start watching on workspace open

### ISSUE THREAD

**Issue by mcpower** [vitest-dev/vscode#197]
**Is your feature request related to a problem? Please describe.**
As a person running tests,
I need to click the "Vitest" button on the status bar every time I open a workspace
So that I can see my test results and test coverage (#136, or by using [vscode-coverage-gutters](https://github.com/ryanluker/vscode-coverage-gutters), which has a similar issue: https://github.com/ryanluker/vscode-coverage-gutters/issues/236) when I modify code

**Describe the solution you'd like**
A config option that, when enabled, automatically starts watching Vitest when a workspace is opened.

**Describe alternatives you've considered**
Automatically running tests on save is another way of achieving this. vscode-jest has _both_ a watch run mode and a on-save run mode.

**Additional context**
I'm coming from the [vscode-jest](https://github.com/jest-community/vscode-jest) which does this by default. See [the `runMode` config option](https://github.com/jest-community/vscode-jest#runmode) of that extension for more details.

**Comment by mrpinkcat** [comment]
This would be a nice addition, especially for the integration in `.settings` file.

**Comment by ffMathy** [comment]
Fixed by #238
