### ISSUE TITLE
Errors not diplayed in vscode with Vitest 1.0.1

### ISSUE THREAD

**Issue by groomain** [vitest-dev/vscode#198]
**Describe the bug**
Errors are empty with vitest v1.0.1.
It's working when I got back to an older version

**To Reproduce**
Install vitest v1.0.1 and you'll not have the errors displayed in vscode. It's working with vitest v0.35.6

**Expected behavior**
Display inline errors in vscode

**Screenshots**
<img width="1001" alt="Capture d’écran 2023-12-06 à 11 22 40" src="https://github.com/vitest-dev/vscode/assets/3601848/fb2f4419-d128-4384-b0b4-81ef4728261e">

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOD
- VSCode version: 1.84.2
- Vitest version: 1.0.1
- Vitest plugin version: 0.2.43

**Comment by mzietlow** [comment]
We are experiencing the same bug on Windows with Vitest version 1.0.2

**Comment by SonyStone** [comment]
Same issue with Vitest 1.0.4
![image](https://github.com/vitest-dev/vscode/assets/8790196/dfcb76b3-093a-4ab2-8ca3-b85a8bebe162)

* OS: Windows 11
* VSCode vesrion 1.84.2
* Vitest 1.0.4
* Vitest plugin version: 0.2.43

**Comment by TonyLomartire** [comment]
Also ran into this on macOS, downgrading resolved.

**Comment by CaptainCodex** [comment]
Confirmed broken on `0.2.43` (1 month ago) and working on `0.2.42` (5 months ago).

**Comment by snake-poison** [comment]
Running into the same issue and after downgrading/upgrading a few times I narrowed down the breaking change in vitest to have been introduced in version `vitest@1.0.0-beta.3`. The latest version that is unaffected by this issue is `vitest@1.0.0-beta.2`.

**Comment by jd1378** [comment]
what's the immediate action we can take to solve the issue locally for now until this is fixed ?

**Comment by cbush06** [comment]
I'm having the same issue. Please fix! This is such a great plugin.

**Comment by MilanKovacic** [comment]
Extension was not updated to properly work with vitest >= 1.0.0. Fixed by https://github.com/vitest-dev/vscode/pull/213.
