### ISSUE TITLE
Vitest version not detected when workspace path has spaces in it

### ISSUE THREAD

**Issue by mzietlow** [vitest-dev/vscode#200]
**Describe the bug**

When starting vscode in a folder whose path contains a blank space (e.g. `C:\The Path\To My\Project`), the vitest-extension is unable to find vitest inside node_modules, throwing two exceptions:

<img src="https://github.com/vitest-dev/vscode/assets/30702083/5957641e-087d-4f06-b884-e8d97dcb4f65" width="50%" height="50%">

After switching from `C:\The Path\To My\Project` to `C:\The_Path\To_My\Project` the vitest plugin was loading correctly again. This was also one of the workarounds mentioned in #88.

**To Reproduce**

1. Open vscode in a folder whose path has spaces in it.
2. Install the vscode vitest extension.
3. Create a new package that has vitest installed (e.g. via `npm init vue@3`).
4. Restart vscode, open the package.
5. => The error appears.

**Environment**

- OS: Win10
- VSCode version: 1.85
- Vitest version: 1.0.2
- Vitest plugin version: 0.2.43

**Additional context**

Perhaps this is related to #88, #170, #116.

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
