### ISSUE TITLE
how to start from project root?

### ISSUE THREAD

**Issue by dcsan** [vitest-dev/vscode#202]
I have an app with structure like `/src/tests/some.test.ts`
there are some `.env` files located at project root.

when I use the testrunner it will instead start from inside the test folder, so no ENV files are loaded, there is no configuration.

this seems the normal setup that everyone would have (for a server side app anyway)

I can run from the cli just fine, starting at the right place.

how do I configure vitest to run from the project root?

**Comment by ffMathy** [comment]
Does workspace support help? https://vitest.dev/guide/workspace

**Comment by sheremet-va** [comment]
The extension now (pre-release 0.5.0 and higher) uses config files as the root. Note that the extension now requires Vitest 1.4.0 or higher.
