### ISSUE TITLE
'View as Tree' option not working

### ISSUE THREAD

**Issue by cassmtnr** [vitest-dev/vscode#204]
**Describe the bug**
It seems that the 'View as Tree' option is not working in the latest versions

**To Reproduce**
- Click in the extension button in the side menu 
- Click in the 3 dots menu
- Select 'View as Tree'

**Expected behavior**
Should display the tests as a tree view

**Screenshots**
![image](https://github.com/vitest-dev/vscode/assets/12648633/7f2a8676-8612-424f-b61a-2c3ebbfc82c6)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS
- VSCode version: 1.85.1
- Vitest version: 1.0.0
- Vitest plugin version: v0.2.43

**Comment by MilanKovacic** [comment]
Extension was not updated to properly work with vitest >= 1.0.0. Fixed by https://github.com/vitest-dev/vscode/pull/213.
