### ISSUE TITLE
no tests displayed with vitest 1.1.0

### ISSUE THREAD

**Issue by christophsturm** [vitest-dev/vscode#206]
**Describe the bug**
when i bump the vitest dependency to 1.1.0 in the example project i no longer see tests

**To Reproduce**
edit package.json to use latest releases of vite and vitest:
```
  "devDependencies": {
    "envinfo": "^7.8.1",
    "vite": "^5.0.10",
    "vitest": "^1.1.0"
  }
```

1. Go to 'testing tab in vscode'
2. it says "no tests have been found in this workspace yet"

**Expected behavior**

**Screenshots**
<img width="356" alt="image" src="https://github.com/vitest-dev/vscode/assets/1999/ac7c5cf2-4553-4ad0-a1f7-500f364b8c63">

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))
```{
  "System": {
    "OS": "macOS 14.2.1"
  },
  "Binaries": {
    "Node": {
      "version": "21.5.0",
      "path": "/opt/homebrew/bin/node"
    },
    "Yarn": {
      "version": "1.22.19",
      "path": "/opt/homebrew/bin/yarn"
    },
    "npm": {
      "version": "10.2.4",
      "path": "/opt/homebrew/bin/npm"
    }
  },
  "IDEs": {
    "VSCode": {
      "version": "1.85.1",
      "path": "/usr/local/bin/code"
    }
  },
  "npmPackages": {
    "vite": {
      "installed": "5.0.10",
      "wanted": "^5.0.10"
    },
    "vitest": {
      "installed": "1.1.0",
      "wanted": "^1.1.0"
    }
  }
}%                         ```

**Comment by 13OnTheCode** [comment]
I'm in a similar situation too.

**Comment by watonyweng** [comment]
Hi @christophsturm, you may need to run `node setup.mjs` first, then append `"vitest.enable": true`  to `.vscode/settings. json` file, and finally reopen VSCode.

**Comment by christophsturm** [comment]
that fixes it. now I just need to find out why it does not run in my monorepo.

it would be really helpful if you updated all the sample projects to vitest 1.1.0

**Comment by cyrfer** [comment]
I just created a new monorepo, added a `vitest.workspace` file, and multiple packages depend on vitest. I can run vitest in the CLI with no problem, at the workspace level and for each package.

I installed this vscode extension and vscode's `Testing` tab shows "No tests have been found in this workspace yet" (same as OP).

I added `"vitest.enable": true` to `.vscode/settings.json`, and restarted vscode. No luck.

What is `setup.mjs`?

**Comment by ennioVisco** [comment]
> I just created a new monorepo, added a `vitest.workspace` file, and multiple packages depend on vitest. I can run vitest in the CLI with no problem, at the workspace level and for each package.
> 
> I installed this vscode extension and vscode's `Testing` tab shows "No tests have been found in this workspace yet" (same as OP).
> 
> I added `"vitest.enable": true` to `.vscode/settings.json`, and restarted vscode. No luck.
> 
> What is `setup.mjs`?

They refer to [this file](https://github.com/zxch3n/vitest-ext-basic-example/blob/master/setup.mjs) from the sample project you should use for reproductions

**Comment by jseto** [comment]
> Hi @christophsturm, you may need to run `node setup.mjs` first, then append `"vitest.enable": true` to `.vscode/settings. json` file, and finally reopen VSCode.

Not working for me. Didn't get any message when the test fails, only the red icon.

This is the output from setup

```
{
  "System": {
    "OS": "Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)"
  },
  "Binaries": {
    "Node": {
      "version": "20.9.0",
      "path": "~/.nvm/versions/node/v20.9.0/bin/node"
    },
    "Yarn": "Not Found",
    "npm": {
      "version": "10.2.1",
      "path": "~/.nvm/versions/node/v20.9.0/bin/npm"
    }
  },
  "IDEs": {
    "VSCode": {
      "version": "1.85.1",
      "path": "/usr/bin/code"
    }
  },
  "npmPackages": {
    "vite": {
      "installed": "5.0.11",
      "wanted": "^5.0.11"
    },
    "vitest": {
      "installed": "1.1.3",
      "wanted": "^1.1.3"
    }
  }
}
```

**Comment by brion-fuller** [comment]
I believe this is similar to https://github.com/vitest-dev/vscode/issues/198#issuecomment-1894334229

**Comment by joshhsiao333** [comment]
Successful fixed by blow steps:

clone blow git repo
`git clone https://github.com/zxch3n/vitest-ext-basic-example.git`

Run 
`node setup.mjs. `
It will Install deps
Update Vitest extension to the latest pre-release version
Unify Vitest settings
Log env info to info.txt

if 'C:\Users\xxxx\AppData\Local\Programs\Microsoft' is not recognized as an internal or external command' error occurred. Modify line 44 of setup.mjs to 
\`"${code}" --install-extension zixuanchen.vitest-explorer --pre-release --force\`
This will fix setup.mjs when vscode installation path contains spaces

Open/Reload this project in VS Code
Test Vitest extension on this project.

**Comment by MilanKovacic** [comment]
This issue will be resolved when https://github.com/vitest-dev/vscode/pull/213 lands.
