### ISSUE TITLE
how to exclude suggestion from vitest/dist in vscode?

### ISSUE THREAD

**Issue by Hunnnn77** [vitest-dev/vscode#210]
# Description
vitest/dist/reportersSOMETHING.js has shown whenever typing(triggering suggestion)
i wanna exclude/remove it but failed.
Here is my setting,

# Settings
# .vscode/settings.json
```
"typescript.tsdk": "node_modules/typescript/lib",
  "typescript.preferences.autoImportFileExcludePatterns": [
      "node_modules/vitest",
      "**/node_modules/vitest",
  ],
```
# tsconfig
```
"exclude": [
    "node_modules",
    "**/node_modules/*"
]
```

**Comment by MilanKovacic** [comment]
Please open the issue in https://github.com/vitest-dev/vitest repository. This repository relates to the Vitest Visual Studio Code extension.
