### ISSUE TITLE
`expect(wrapper.emitted('update:modelValue')).toHaveLength(1)`  is undefined

### ISSUE THREAD

**Issue by seaneez** [vitest-dev/vscode#211]
**Describe the bug**

Testing the wrapper.emitted('update:modelValue') function results in an error, although it operates correctly when executed via the command line interface using `npm run test`.

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Make a vue component having modelValue as a props and emitting `update:modelValue`

```
// MyComponent.vue
<template>
    <input style="border: solid 1px black" :value="modelValue" @input="onInput" />
</template>

<script lang="ts">
import { defineComponent } from 'vue';


export default defineComponent({
    props: {
        modelValue: { type: String, default: '' },
    },
    emits: ['update:modelValue'],
    setup(props, { emit }) {
        const onInput = (event) => {
            emit('update:modelValue', event.target.value);
        };
        return {
            onInput,
        };
    },
});
</script>
```

2. Make a testcode for this component using `wrapper.emitted()` fn
```
        it('update: modelValue test', async () => {
            // given
            const wrapper: ReturnType<typeof mountComponent> = mount(VsTabs, {
                props: {
                    modelValue: '',
                    'onUpdate:modelValue': (e: number) => wrapper.setProps({ modelValue: e }),
                },
            });

            // when
            await wrapper.find('input').setValue('test');

            // then
            expect(wrapper.props('modelValue')).toBe('test');
            expect(wrapper.emitted('update:modelValue')).toHaveLength(1);     // Target cannot be null or undefined Error occurs
        });
```

**Expected behavior**
The test should be passed

**Screenshots**

**Environment**
- node version 18.16.1 and 20.4.0 (both)
- "vite": "^4.4.5",
- "vitest": "^0.34.6",  (In a higher version, the error message does not appear, but it still fails)
- "vue": "^3.3.4",  

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: [e.g. macOS] window
- VSCode version: 1.85
- Vitest version: "^0.34.6",  (In a higher version, the error message does not appear, but it still fails)
- Vitest plugin version: v0.2.43

**Additional context**

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
