### ISSUE TITLE
Include and exclude paths are not imported from either the vitest config file or the vite config file

### ISSUE THREAD

**Issue by stuymedova** [vitest-dev/vscode#215]
**Describe the bug**
While vitest itself works correctly and ignores the files that don't match the config include statement, the extension doesn't. Adding the include statement to extension settings helps.

**Expected behavior**
Include and exclude paths are imported from either the vitest config file or the vite config file.

**Environment**
- OS: macOS Monterey
- VSCode version: 1.85.1
- Vitest version: 1.0.4
- Vitest plugin version: 0.2.43

**Comment by alexrecuenco** [comment]
I am having the same issue (macOS Sonoma)

**Comment by MilanKovacic** [comment]
Extension was not updated to properly work with vitest >= 1.0.0. Fixed by https://github.com/vitest-dev/vscode/pull/213.
