### ISSUE TITLE
Add grammar for snapshot files

### ISSUE THREAD

**Issue by segevfiner** [vitest-dev/vscode#216]
**Is your feature request related to a problem? Please describe.**
Snapshot files have no syntax highlighting

**Describe the solution you'd like**
Add a grammar for snapshot files, like the Jest VS Code extension has.

**Describe alternatives you've considered**
Keep staring at them with no syntax highlighting

**Additional context**
https://github.com/jest-community/vscode-jest/blob/master/syntaxes/jest-snapshot.tmLanguage

**Comment by sheremet-va** [comment]
Closed by 1046e0b1ba7fb74ed560eb704a26dd0415719dce
