### ISSUE TITLE
Run with different vitest configuration file

### ISSUE THREAD

**Issue by hornta** [vitest-dev/vscode#217]
Not sure this project already supports this but in our project we have two different vitest configuration files. One for simple unit tests, and one for our integration tests. When I execute a test from the gutter in an integration test file, this plugin incorrectly selects the configuration file for our unit tests, despite that file explicitly excludes the file I'm trigger the test from.

It would be nice if vitest could figure out the correct vitest config from the file path. Vitest could scan all files matching `vitest.*.config.ts`, and from looking at the `include/exclude` arrays it could select the best config. 

My configs for reference:
```ts
// vitest.config.ts
export default defineConfig({
  test: {
    exclude: [
      "**/*.integration.test.ts",
    ],
  },
});

// vitest.integration.config.ts
export default defineConfig({
  test: {
    include: ["**/*.integration.test.ts"],
});
```

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.

We now create separate test profiles for each vitest.config.
