### ISSUE TITLE
Because Vitest version < 0.12.0, run/debug/watch tests are disabled in workspace "@foo/bar"

### ISSUE THREAD

**Issue by moltar** [vitest-dev/vscode#219]
**Describe the bug**

Not sure if it can be qualified as a bug, but it is certainly a UX/DX issue.

When running in a multi-folder workspace, the following error gets reported for projects (packages) that do not have _any_ Vitest version installed:

> Because Vitest version < 0.12.0, run/debug/watch tests are disabled in workspace "@foo/bar"

**To Reproduce**

1. Use multi-folder workspace.
2. Add one package without vitest
3. Open VS Code

**Expected behavior**

IMO, if there's no vitest dep, I think the extension should skip over and not report anything. Not every package needs vitest.

**Screenshots**

![screenshot-20240205T134317-U2GLMIro@2x](https://github.com/vitest-dev/vscode/assets/491247/ddc9b312-5fbb-4717-8672-460e3b7c2015)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS
- VSCode version: 
- Vitest version: N/A
- Vitest plugin version: v0.2.43

**Additional context**

I'm aware that `vitest.disabledWorkspaceFolders` exists, and can help, if a project is included here explicitly. But feels like this should be the default behaviour.

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
