### ISSUE TITLE
Make it official

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vscode#22]
Thank you @zxch3n and contributors making and maintaining this extension. After the discussion with the team, we are happy to make this extension our official one and maintain it in the org together.

@zxch3n I have sent you the invitation to join the team, if you'd like, you can transfer this repo into the org (ping me to set up the permissions if needed). And you can send PR to fulfill your info in our docs.

Cheers!

**Comment by zxch3n** [comment]
Cheers!
