### ISSUE TITLE
Peek view is empty although test output shows errors

### ISSUE THREAD

**Issue by juni0r** [vitest-dev/vscode#220]
When running a test that fails, peek view will be empty. The output has the information though. It just doesn't end up in peek view.

**Screenshots**
<img width="778" alt="Screenshot 2024-02-13 at 11 25 30" src="https://github.com/vitest-dev/vscode/assets/11867/dd59a1a6-4817-407a-affb-312362b18201">

**Environment**

- macOS
- VSCode 1.86.1
- Vitest 1.2.2 darwin-arm64 node-v20.11.0
- Vitest plugin 0.2.43

**Vitest plugin Config**
```json
{
  "vitest.enable": true,
  "vitest.commandLine": "yarn vitest",
  "vitest.exclude": [    
    "**/node_modules/**",
    "**/dist/**",
    "**/e2e/**",
    "**/.{nuxt,git,cache,output,temp}/**"
  ],
  "vitest.showFailMessages": true,
}
```

**Comment by TristanSpeakEasy** [comment]
I am experiencing this as well

**Comment by MilanKovacic** [comment]
Extension was not updated to properly work with vitest >= 1.0.0. Fixed by https://github.com/vitest-dev/vscode/pull/213.
