### ISSUE TITLE
Exclude and include should not be extension settings

### ISSUE THREAD

**Issue by ffMathy** [vitest-dev/vscode#233]
**Describe the bug**
Today, two settings (`vitest.include` and `vitest.exclude`) exist. In my opinion, because of their defaults, it just adds more confusion. Why not use the include of the vitest config of the project?

The default pattern is also `'**/*.{test,spec}.?(c|m)[jt]s?(x)'`, which will include `node_modules` and a lot of other garbage (900 files instead of 22 for my repo). It took me hours to figure out that it was due to this, because I had already configured exclude and include in my vitest config.

**Comment by ffMathy** [comment]
Actually, we can also see it is a big cause of bad reviews here: https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer&ssr=false#review-details

To be honest, even though it's a breaking change, I think it's worth a major version for.

@MilanKovacic if you think it's worth it, I can make a PR that implements this, along with a version bump.

**Comment by sheremet-va** [comment]
We are releasing it as a separate extension, so it's fine to bump it.
