### ISSUE TITLE
In an nx monorepo set the working directory to the package directory

### ISSUE THREAD

**Issue by chriswheeldon-peakon** [vitest-dev/vscode#254]
When running tests in an nx monorepo (e.g. the `monorepo-nx` sample) the working directory is set to the monorepo root. However, when the tests are executed using nx (e.g. `nx run-many -t test` or `nx test <package>`) the working directory is set to the package directory.

Ideally the extension would be consistent with nx and change to the package directory before executing tests.

A workaround right now is to set up a [multi-root vscode workspace](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces) with an entry for each package directory e.g. for the monorepo-nx sample:

```json
{
  "folders": [
    {
      "path": "node"
    },
    {
      "path": "library"
    }
  ],
  "settings": {
    "vitest.enable": true
  }
```

**Comment by chriswheeldon-peakon** [comment]
cc @ffMathy - from our conversation on https://github.com/vitest-dev/vscode/pull/231 🙏

**Comment by sheremet-va** [comment]
I don't think this is in the scope of this extension. Vitest itself doesn't support nx integration, it has its own [workspace support](https://vitest.dev/guide/workspace.html).

**Comment by ffMathy** [comment]
But when we have a vitest.workspace.ts file, is Vitest's behavior then to set the root directory to the workspace folder, or the root folder?

Either way, I think I'll update the NX sample to mimick NX behavior more. I think it's doable.

**Comment by sheremet-va** [comment]
> But when we have a vitest.workspace.ts file, is Vitest's behavior then to set the root directory to the workspace folder, or the root folder?
> 
> Either way, I think I'll update the NX sample to mimick NX behavior more. I think it's doable.

`vitest.workspace.ts` file should be supported, yes. We cannot support `nx vitest` behavior though.

**Comment by chriswheeldon-peakon** [comment]
@sheremet-va when you say "We cannot support nx vitest behavior though." do you mean in this extension or generally in vitest?

Having thought about it some more I can clearly see that this, as you said, is beyond the scope of this extension. The issue here would seem to stem from the fact that nx will change directory into the package directory when running package commands whereas vitest will not do this, even in the presence of a vitest workspaces file.

Is it worth opening a discussion on this in the vitest repo? From reading the vitest workspaces [docs](https://vitest.dev/guide/workspace) and in particular this line "Vitest will consider every folder in packages as a separate project even if it doesn't have a config file inside.", I think it can be argued that vitest should change directory when executing package tests. My experience here is limited, but I think this would also be consistent with other monorepo tooling (f.ex nx, npm -w).

**Comment by sheremet-va** [comment]
Yes, it should change the directory for projects. And from my knowledge, it already does so (when you use the workspace feature of course). If it doesn't for you, I would suggest opening an issue with a reproduction in Vitest repo.

**Comment by sebastien-comeau** [comment]
I tried everything base on the [official instruction](https://vitest.dev/guide/workspace.html) and no success with [our monorepo](https://github.com/DTS-STN/canadian-dental-care-plan). Only the `frontend` directory is using vitest. We are using playwright extension and it works without any extra configuration.

```
[INFO 12:29:12 PM] The extension is not activated because no Vitest environment was detected.
```

**Comment by sheremet-va** [comment]
This is the behavior of Vitest and not the extension. The `vitest.workspace` file doesn't change the working directory of its projects because it's not supported in workers. You can bypass this by adding a setup file that changes the directory like this for example:

```ts
import { resolve } from 'node:path'
process.chdir(resolve('../project-1'))
```

**Comment by chriswheeldon-peakon** [comment]
@sheremet-va I don't that is viable as you are not allow to chdir in a worker.

**Comment by sheremet-va** [comment]
> @sheremet-va I don't that is viable as you are not allow to chdir in a worker.

Sorry, I forgot to mention to also use `pool: 'forks'`.
