### ISSUE TITLE
Windows Run Tests still failing

### ISSUE THREAD

**Issue by xon52** [vitest-dev/vscode#27]
Unfortunately I still have a windows bug where tests are instantly failing.
The output file does not exist in this case so I will investigate some more:
![image](https://user-images.githubusercontent.com/30713944/165522971-274e952f-c674-49f0-bef5-48c653862c08.png)

When I pull this extension and use locally, I can successfully Run Tests with expected results which makes this a lot harder to debug:
![image](https://user-images.githubusercontent.com/30713944/165523332-f9fc5c0e-ca69-491c-ace2-372c6aecc6fe.png)

**Comment by zxch3n** [comment]
What is your vitest version? If you open `samples/basic` project directly in your vscode, does the extension work?

**Comment by xon52** [comment]
@zxch3n good question. Yes it does! For Run Tests, not Debug Tests though.
Do you have any idea why this works in `samples/basic` and not in my other project?

**Comment by zxch3n** [comment]
Is one of your projects open source? Or can you make a minimal reproducible project?

**Comment by xon52** [comment]
@zxch3n minimal reproduction is just a test file:
![image](https://user-images.githubusercontent.com/30713944/165741346-26e9c657-c02e-4388-a105-8204c2ad8f3d.png)

But I think I've found the issue for my Debug Tests - will test out and put another PR in if it works:
![image](https://user-images.githubusercontent.com/30713944/165741855-5a97c15b-8f78-4df1-8c42-07dfdca6c2a3.png)

**Comment by zxch3n** [comment]
> @zxch3n minimal reproduction is just a test file:

Please upload this example to GitHub or CodeSanbox. Otherwise, I don't know what your configure looks like. Can you run vitest successfully in the shell?

**Comment by xon52** [comment]
Run tests now works in v0.1.21. Debug doesn't, but it didn't before and Run was my main concern 🎉
