### ISSUE TITLE
vitest.workspace.json not discovering Tests

### ISSUE THREAD

**Issue by ldrick** [vitest-dev/vscode#271]
### Describe the bug

I have a workspace like that:
```
./frontend/projectA/vite.config.ts
./frontend/projectB/vite.config.ts
./backend
./not-a-npm-project
./e2e-tests
```
Right now I'd like to use the `./vitest.workspace.json` because this is not a monorepo, neither it works well with vscode multi-root-workspaces due to many old school setup not so easy to change.

Unfortunately vitest vscode doesn't recognize the file or at least tests from both frontend-projects do not show up.

### Reproduction

This is the vitest.workspace.json:

```json
["frontend/*/vite.config.ts"]
```

### System Info

```shell
I am working within WSL2 hosted in Windows 11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The extension was rewritten from the ground up in #253.

It should now support `vitest.workspace.json` file out of the box.
