### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by equiman** [vitest-dev/vscode#29]
I would recommend changing to Icon to easily associate the extension with a Test Explorer Adapter.

I've created this Icon inspired by the other Adapters:
![vitest-icon](https://user-images.githubusercontent.com/933393/167235641-fc894d64-5dc6-41e1-ab50-e53be16404ee.png)

**Comment by zxch3n** [comment]
This extension is not based on Test Explorer UI. It's built upon [VSCode Testing API](https://code.visualstudio.com/api/extension-guides/testing)
