### ISSUE TITLE
v0.5.2 does not have the "open" tag anymore

### ISSUE THREAD

**Issue by ffMathy** [vitest-dev/vscode#297]
### Describe the bug

The open-tag introduced in #237 is no longer available as of 0.5.0. Can we re-introduce it? It's a killer feature in my opinion.

### Reproduction

Open a test file. The "@vitest:open" tag is no longer there.

### System Info

```shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ffMathy** [comment]
Curious as to the `p2-nice-to-have`, as it is technically a regression right? It's an advertised feature that is being removed, I suppose?

And if that's the case, we should at least remove its reference from the README.md. But very sad to see this one go in that case 🙁

**Comment by sheremet-va** [comment]
Just reimplement it, 0.5.0 is a pre-release, it doesn't have half the functionality we had before.
