### ISSUE TITLE
Vitest nodejs tests do not run - CAC error

### ISSUE THREAD

**Issue by nathanielfinkgapmaps** [vitest-dev/vscode#304]
### Describe the bug

Looks like it's having trouble with another library.  Debug console says "Please start a debug session to evaluate expressions". There doesn't seem to be any discussion about this anywhere.

```
/home/user/.nvm/versions/node/v18.19.1/bin/node ./node_modules/vitest/vitest.mjs run vitest --silent=false --disable-console-intercept path/__test__/test.mjs -t Test Controller Test testUnit --api.port 36015 --api.host 127.0.0.1
Uncaught CACError CACError: Unknown option `--disableConsoleIntercept`
    at checkUnknownOptions (path/node_modules/cac/dist/index.mjs:400:17)
    at runMatchedCommand (path/node_modules/cac/dist/index.mjs:598:13)
    at parse (path/node_modules/cac/dist/index.mjs:537:12)
    at <anonymous> (path/node_modules/vitest/dist/cli.js:72:7)
    at run (internal/modules/esm/module_job:195:25)
No debugger available, can not send 'variables'
Process exited with code 1

```

### Reproduction

Run any test from within vscode

### System Info

```shell
Ubuntu 23.10, vscode 1.87.2, vitest 0.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The latest version is 0.5.6 (pre-release).

**Comment by nathanielfinkgapmaps** [comment]
> The latest version is 0.5.6 (pre-release).

Happens in this version as well.  It looks like it's happening somewhere in the vitest code. There is no string --disableConsoleIntercept anywhere that I can see, though.  So I don't know why it's complaining about this option.

**Comment by nathanielfinkgapmaps** [comment]
Turned out to be an issue with conflicting module versions
