### ISSUE TITLE
vitest.commandLine is gone in 0.5?

### ISSUE THREAD

**Issue by appcoders** [vitest-dev/vscode#306]
### Describe the bug

In my package.json I defined 
```
    "test": "DOTENV_CONFIG_PATH=.env.testing LOG_LEVEL=debug vitest",
```
and in vscode settings:
```
"vitest.commandLine": "yarn test --"
```
This works on vitest vscode 0.4.2 - on newer versions >0.5 the vitest.commandLine is gone and tests cannot be loaded at all because the environment variables are missing.

![CleanShot 2024-03-19 at 11 00 27@2x](https://github.com/vitest-dev/vscode/assets/4519870/8863ac5e-4b75-4efc-82b2-70f5fbabdd07)

### Reproduction

See above.

### System Info

```shell
devcontainer on macOS 14.4:

System:
    OS: Linux 6.5 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (10) arm64 unknown
    Memory: 2.66 GB / 11.67 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/share/npm-global/bin/pnpm
  IDEs:
    Nano: 5.4 - /bin/nano
    VSCode: 1.87.2 - /vscode/vscode-server/bin/linux-arm64/863d2581ecda6849923a2118d93a088b0745d9d6/bin/remote-cli/code
  npmPackages:
    @vitest/ui: ^1.4.0 => 1.4.0 
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, `vitest.commandLine` doesn't exists anymore as an option.

**Comment by appcoders** [comment]
@sheremet-va Thanks - so what is the migration path to inject environment variables?

**Comment by sheremet-va** [comment]
`vitest.nodeEnv` is still supported

**Comment by appcoders** [comment]
@sheremet-va 
Besides the fact, it would be cumbersome to manage environment variables in two different files, it does not work:

![CleanShot 2024-03-19 at 11 00 23@2x](https://github.com/vitest-dev/vscode/assets/4519870/2d8c8e33-7e9a-455f-869c-97c0792a5b4d)

**Comment by sheremet-va** [comment]
> it would be cumbersome to manage environment variables in two different files

The extension doesn't use Vitest CLI, so it is not possible to define a command line. If you have an environment-specific env, the recommended way is to define a `.env.{name}` file: https://vitejs.dev/guide/env-and-mode.html#env-files

It is picked up automatically.

If your test environment is different, you can have a `.env.test` file:

```
VITE_DOLPHIN_URL=url
```

> it does not work

I cannot help you without a reproduction. `vitest.nodeEnv` works on my side: 

https://github.com/vitest-dev/vscode/blob/99f2faf8a84becd42f3fada816ad23ef44a29bd1/samples/basic/test/env.test.ts#L8

**Comment by mwood23** [comment]
I use a custom bash script to configure my test environment. Using a command line option would be very valuable to me. It's normal for integration test suites to require advanced configured to run tests. Thanks for the repo, just putting in my two cents!

**Comment by sheremet-va** [comment]
> It's normal for integration test suites to require advanced configured to run tests.

Could you move it to `globalSetup`? If not, would an option to just run something before tests be enough? 

> 1. Run external code
> 2. Start Vitest watcher
> 3. Run teardown when vscode is closed

**Comment by mwood23** [comment]
Maybe if I had a before tests thing to set environmental variables. My API integration test suite is pretty complicated to setup so the bash script is definitely preferable compared to spawning child process and doing that sorta stuff in global setup.
