### ISSUE TITLE
"Test result not found" but tests run fine in CLI

### ISSUE THREAD

**Issue by paul-uz** [vitest-dev/vscode#307]
### Describe the bug

The plugin is giving me "Test result not found." for random tests. Running vitest via the CLI results in all tests passing.

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 76.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.6.11 - /opt/homebrew/bin/pnpm
    bun: 1.0.3 - /opt/homebrew/bin/bun
  IDEs:
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by paul-uz** [comment]
I cannot reproduce as it requires VSCode itself.

**Comment by paul-uz** [comment]
Anyone else getting this behaviour?

It's happens somewhat randomly and reproduction is near impossible but it does indeed happen.

**Comment by jcarrus** [comment]
I've run into this issue a few times, @paul-uz I would verify that:

- there are no other tests with the same name as the test that cannot find results
- there is no code in the .spec/test that fails/throws. If there is an uncaught exception, but it's not within the `describe(` or `test(` or `it(`, the error isn't surfaced and you get the "test result not found" error.
