### ISSUE TITLE
Known issues with pre-release

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vscode#314]
### Describe the bug

This report is a collection of known issues related to the latest pre-release. This list only has features that were working prior to the pre-release version. The fact that the issues are known doesn't mean someone is working on a fix. If you can help, please open a pull request with fixes.

- https://github.com/vitest-dev/vscode/issues/287
- https://github.com/vitest-dev/vscode/issues/297
- https://github.com/vitest-dev/vscode/issues/289
- https://github.com/vitest-dev/vscode/issues/285
- https://github.com/vitest-dev/vscode/issues/295
- https://github.com/vitest-dev/vscode/issues/294
- https://github.com/vitest-dev/vscode/issues/317
- https://github.com/vitest-dev/vscode/issues/320

**Comment by oenu** [comment]
Another possible issue (adding here before making an issue card), seems that the extension might not be respecting the threads limits in a config file. I am using canvas so have to disable multithreads, so get `Module did not self-register` errors in the Test explorer but not my cli. Happy to provide more details if needed

**Comment by sheremet-va** [comment]
> Another possible issue (adding here before making an issue card), seems that the extension might not be respecting the threads limits in a config file. I am using canvas so have to disable multithreads, so get `Module did not self-register` errors in the Test explorer but not my cli. Happy to provide more details if needed

Please, create a separate issue with a reproduction.
