### ISSUE TITLE
Error when instansiating a class with an enviroment variable

### ISSUE THREAD

**Issue by samducker** [vitest-dev/vscode#325]
### Describe the bug

This issue only seems to happen when upgrading to the pre-release version of VSCode which I did to fix another error I was previously having which was recommend by this github repo.

When I am initiating the resend library I am getting the following error.

```
 FAIL  src/app/api/survey/recruit/tests/recruit.test.ts [ src/app/api/survey/recruit/tests/recruit.test.ts ]
Error: Missing API key. Pass it to the constructor `new Resend("re_123")`
 ❯ new Resend node_modules/resend/dist/index.mjs:325:15
    323|       }
    324|       if (!this.key) {
    325|         throw new Error(
       |               ^
    326|           'Missing API key. Pass it to the constructor `new Resend("re_123")`'
    327|         );
```

My implementation

```
import { beforeEach, expect, test } from "vitest";
import { loadEnvConfig } from "@next/env";
import { Resend } from "resend";

beforeEach(async () => {
  loadEnvConfig(process.cwd());
});

test("send survey started / payment confirmed email", async () => {
  const resend = new Resend(process.env.RESEND_API_KEY);
  const generateId = () => Math.random().toString(36).substring(7);
  const fakeSurveyId = generateId();
  const fakePaymentIntent = "pi_" + generateId();

  const { data, error } = await resend.emails.send({
    from: "Some company <support@mycompany.com>",
    to: "sam@mycompany.com",
    subject: "Your survey is live!",
    react: PaidSurveyLive({
      survey: {
        audience: "uk",
        question:
          "How likely are people to support a coffee brand that is environmentally friendly (test)",
        size: 1,
        id: fakeSurveyId,
      },
      paymentDetails: {
        date: new Date().toDateString(),
        discount: 0,
        total: 7900,
        paymentIntentId: fakePaymentIntent,
        paymentMethod: {
          type: "other",
          last4: "4242",
        },
        subtotal: 7900,
        tax: 0,
      },
      enviroment: process.env.NEXT_PUBLIC_ENVIROMENT === "production" ? "production" : "staging",
      previewText: "Your survey is live! Click the button below to view your survey results.",
    }),
  });

  expect(data).toBeDefined();
  expect(error).toBeNull();
});
```

### Reproduction

I'm not sure how I could reproduce this as it is related to local enviorment variables. 

### System Info

```shell
I'm using Next.js 14 with .env file
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> I'm not sure how I could reproduce this as it is related to local enviorment variables.

I need a repository that I can open in VSCode and see the error. It doesn't matter if the code is the same that you have right now - you can use code from examples and create a reproducible repo there.
