### ISSUE TITLE
Running test on the `packages` folder of a workspace does nothing - v0.5.13 (pre-release)

### ISSUE THREAD

**Issue by timotheeguerin** [vitest-dev/vscode#331]
### Describe the bug

When working in a vitest workspace and trying to run the test on a folder above the project(e.g. `packages`) it does nothing with the pre-release extension (0.5.13). 

I am guessing this is because vitest workspace are not aware themself of the structure above each individual project. 

I am not sure if this is fixable or the tree view should show the project names as the root nodes instead of the folder structure.

Nothing major, thanks a lot for the awesome work in the 0.5.0 rewrite extension feels is feeling much nicer now.

### Reproduction

1. open the workspace example from vitest repo https://github.com/vitest-dev/vitest/tree/main/examples/workspace
2. See this 
![image](https://github.com/vitest-dev/vscode/assets/1031227/aeb35447-538e-443f-bcca-1fb628a0aba9)
3. Select `packages` and click run 

![image](https://github.com/vitest-dev/vscode/assets/1031227/743b35df-a044-4ac9-8cf7-7efcfd92bf85)
4. Result is no test are run 
![image](https://github.com/vitest-dev/vscode/assets/1031227/88b2c752-f9ff-48e1-a982-7fe58c371c08)

### Output

```shell
[INFO 2:15:03 PM] [API] Running Vitest: v1.4.0 (/Users/timotheeguerin/dev/test/vitest-repro/vitest.workspace.ts)
[INFO 2:15:04 PM] [API] Vitest process 73502 created
[INFO 2:15:06 PM] Running 1 file(s): /Users/timotheeguerin/dev/test/vitest-repro/packages/
```

### Version

v0.5.13 (pre-release)

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is fixed in the next Vitest minor (1.5.0) - should be released on Friday.

Related: https://github.com/vitest-dev/vitest/pull/5408
