### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by blakegearin** [vitest-dev/vscode#335]
Type: <b>Bug</b>

Having this extension enabled caused my CPU to stay at 100% usage. Found and reported using VS Code's bisect tool.

Extension version: 0.4.1
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:28:09.495Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 12, 11|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|. --crash-reporter-id 6affc3c0-f111-48d3-828d-5b1c94c5261a|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sheremet-va** [comment]
Try pre-release version.

**Comment by sheremet-va** [comment]
I am going to close this issue because it doesn't follow the template, and doesn't use the latest extension version (which a the moment is 0.5.15)
