### ISSUE TITLE
JSON.parse error different in extention and cli runs

### ISSUE THREAD

**Issue by sf0rman** [vitest-dev/vscode#350]
### Describe the bug

When running test that expects a `JSON.parse` to fail, the error message shown in CLI `vitest run` and runs started from vitest vscode extension differ.

In order to satisfy one, the other will faile.

### Reproduction

Running this test will pass using `vitest run` in the cli and will fail if run from the extension.

```ts
describe("JSON parse errors", () => {
  it("JSON parse", () => {
    expect(() => JSON.parse("JUST SOME TEXT")).toThrowError(
      new SyntaxError("Unexpected token J in JSON at position 0")
    );
  });
});
```
![image](https://github.com/vitest-dev/vscode/assets/4357437/dc6ad648-efb3-4d73-8a12-4c6c7a860a9f)
![image](https://github.com/vitest-dev/vscode/assets/4357437/83b91a51-b964-42fe-91dc-e115c01722e4)

______
Extension v0.6.3

package.json
```
{
  "name": "vitestprob",
  "version": "1.0.0",
  "type": "module",
  "devDependencies": {
    "@types/node": "20.12.7",
    "typescript": "5.4.5",
    "vitest": "1.5.0"
  }
}
```

vitest.config.ts
```
import { defineConfig, UserConfigExport } from "vitest/config";

export default defineConfig({
  test: {
    include: ["**/*.test.ts"],

    environment: "node",
    cache: false,
  },
  logLevel: "info",
  esbuild: {
    sourcemap: "both",
  },
} satisfies UserConfigExport);
```

### Output

```shell
[INFO 10:26:49] Running 1 file(s) with name pattern: ^\s?JSON parse errors JSON parse$
```

### Version

0.6.3

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What Node version do you use in a CLI?

**Comment by sf0rman** [comment]
I was on node 18, but looks like you've completed this. Thanks!
Updated vitest extention and it's all working.
