### ISSUE TITLE
setupFile.mjs not found

### ISSUE THREAD

**Issue by PandharabaleAniketJohnDeere** [vitest-dev/vscode#356]
### Describe the bug

After the Vitest extension update (0.8.1), when I run the tests in VSCode, I get following error:
Failed to load url C:/Users/IKFP9H5/.vscode/extensions/vitest.explorer-0.8.1/dist/setupFile.mjs (resolved id: C:/Users/IKFP9H5/.vscode/extensions/vitest.explorer-0.8.1/dist/setupFile.mjs). Does the file exist?

I can see the file located in the file structure. But tests are not running in VSCode.

### Reproduction

Update/Install the Vitest extension for VSCode.
Name: Vitest
Id: vitest.explorer
Description: A Vite-native testing framework. It's fast!
Version: 0.8.1
Publisher: Vitest
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vitest.explorer

### Output

```shell
Failed to load url C:/Users/IKFP9H5/.vscode/extensions/vitest.explorer-0.8.1/dist/setupFile.mjs (resolved id: C:/Users/IKFP9H5/.vscode/extensions/vitest.explorer-0.8.1/dist/setupFile.mjs). Does the file exist?
```

### Version

0.8.1

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by guysympoly** [comment]
Hi, the same thing happens to me, here's a log of the error I receive

```
[INFO 4:04:25 PM] [v0.8.1] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 4:04:27 PM] [API] Running Vitest: v1.5.0 (vitest.config.ts)
[INFO 4:04:27 PM] [API] Starting Vitest process with Node.js: C:\Program Files\nodejs\node.EXE
[Error 4:04:31 PM] [Error Error] Vitest failed to start: 

r
Error: Vitest failed to start: 

r
    at ChildProcess.u (c:\Users\*****\.vscode\extensions\vitest.explorer-0.8.1\dist\extension.js:13:331)
    at ChildProcess.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```
I'm running vitest in a project using `pnpm` (idk if that actually matters), and I managed to make the extension work only by rolling back to an earlier version (0.6.0).

**Comment by PandharabaleAniketJohnDeere** [comment]
I deleted the VS Code extension folder (C:/Users/IKFP9H5/.vscode/extensions) and installed Vitest plugin again in VSCode. It is working as expected. This happened with my office colleague too. Maybe some cache issue or something with VSCode.
