### ISSUE TITLE
Process doesn't start (Resolving Vitest...)

### ISSUE THREAD

**Issue by fdc-viktor-luft** [vitest-dev/vscode#362]
### Describe the bug

Opening the "Testing" view the process never starts and shows just a spinner on the label "Resolving Vitest..."

<img width="457" alt="Bildschirmfoto 2024-04-22 um 08 12 47" src="https://github.com/vitest-dev/vscode/assets/17571883/add0b477-7993-485f-bdcc-a8c8a1d2f605">

Maybe related: I cannot see any "play" icons in the file view anymore.
<img width="548" alt="Bildschirmfoto 2024-04-22 um 16 07 10" src="https://github.com/vitest-dev/vscode/assets/17571883/cb34c920-42df-474f-80f6-9f30e79befd4">

### Reproduction

The plugin should tell me why it cannot resolve Vitest.

Could reproduce on this repo as well: https://github.com/fdc-viktor-luft/raw-vite-app

Here is my VSCode About:
```
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0
```

Having the same issue under Linux.

### Output

```shell
[INFO 08:06:39] [v0.8.4] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 07:56:57] [API] Running Vitest: v1.5.0 (vitest.workspace.ts)
[INFO 07:56:57] [API] Starting Vitest process with Node.js: /Users/viktor/.nvm/versions/node/v20.12.0/bin/node
```

### Version

0.8.4

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
From a quick look, your setup file looks a bit suspicious. https://github.com/fdc-viktor-luft/raw-vite-app/blob/baf04e23ae11e403f35246fe7090100c3b2156dc/setupTests.ts#L5-L8 Can you check if commenting out them helps anything?

**Comment by fdc-viktor-luft** [comment]
The code wasn't the issue. After updating to plugin version 0.8.5 just now, it works in the reproduction repo inside the "Testing" panel. However, the icons still don't appear, and it doesn't work in another project that has a workspace.

Will try to find some time to create a repro with a workspace.

**Comment by fdc-viktor-luft** [comment]
ok. I made some progress. The issue is highly depending on the amount of workspace packages.

I could only add a maximum of 6 workspace packages into the `vitest.workspace.js`.

Then I can also see this log:

```
[INFO 14:16:17] [API] Vitest process 28577 created
```

The loading takes significantly longer with each added workspace package.

But my current target are 50 workspace packages. However, this never resolves.

**Comment by sheremet-va** [comment]
> But my current target are 50 workspace packages. However, this never resolves.

Is running Vitest from the terminal fast enough with this amount of packages?

**Comment by fdc-viktor-luft** [comment]
I never tried running the workspace using vitest 🙈 This lead finally to seeing the actual error, while the plugin was not responding at all.

Running `vitest run` from the workspace level results in the following error:

```
Error: Project name "typescript" is not unique. All projects in a workspace should have unique names.
```

And it escapes. The plugin should print that error as well.

After I excluded the duplicates the plugin operates normally with roughly 40 workspace packages.
