### ISSUE TITLE
Often blocked by temporary files

### ISSUE THREAD

**Issue by fdc-viktor-luft** [vitest-dev/vscode#363]
### Describe the bug

Seeing errors like the below when I ran e.g. some git commands because of temporary files that appear often for a short time.

I could add these files by pattern to the `.gitignore`, but maybe it makes more sense to generate these files in some other place? Or at least include a hint in the Readme about a required `.gitignore` entry.

### Reproduction

Having a vitest workspace. Don't know when the temporary files get generated.

### Output

```shell
fatal: unable to stat '<private>/some-ui/vite.config.ts.timestamp-1713965378396-ffe28c2cba944.mjs': No such file or directory
```

### Version

0.8.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fdc-viktor-luft** [comment]
I think those files are always generated each time I touch the `vite.config.ts`

**Comment by sheremet-va** [comment]
This is coming from Vite: https://github.com/vitejs/vite/issues/13267
