### ISSUE TITLE
Show assertion/expect failures inline on the line that actually failed

### ISSUE THREAD

**Issue by beorn** [vitest-dev/vscode#37]
Currently test results are shown for the entire test as a whole, which for tests that have several expects makes it hard to figure out what actually failed.

It would be better, IMO, to show the failure where it actually happened in the context of the source code, such as is done with Jest Test Explorer or the terminal runner for vitest - see screenshots.

## Current output

<img width="470" alt="Screen Shot 2022-05-20 at 09 51 55" src="https://user-images.githubusercontent.com/8559/169575817-cf2dfa6e-efab-4cb2-bcd2-5e385d9565b5.png">

## Better - Vitest terminal output

<img width="487" alt="Screen Shot 2022-05-20 at 09 49 38" src="https://user-images.githubusercontent.com/8559/169576011-8c561e01-64d9-4f77-bed8-7bdb30764b43.png">

## Best - Jest explorer - inlined with source code

<img width="557" alt="Screen Shot 2022-05-20 at 09 47 15" src="https://user-images.githubusercontent.com/8559/169576344-1a71ebd6-5174-419d-b3a6-ec85e6cf4a52.png">

**Comment by zxch3n** [comment]
It's supported in the pre-release version now
