### ISSUE TITLE
Debugging twice fails

### ISSUE THREAD

**Issue by ffMathy** [vitest-dev/vscode#374]
### Describe the bug

When I first debug a test, it works just fine. But then when I do it again, I just get a "Debugging failed". This has been existing since the new version of the extension.

### Reproduction

No repro yet - but could use advice on how to repro (and where to perhaps insert more log statements?).

### Output

```shell
[INFO 11:19:36 AM] [DEBUG] Starting debugging on localhost:9229
[INFO 11:19:36 AM] Running 1 file(s) with name pattern: ^\s?Class: CreateVEDTask Use case: Action is always discoverable action is available$
[Worker] Debugger listening on ws://127.0.0.1:9229/936930f0-6b4c-4f66-bf18-93973dbb8cc2
For help, see: https://nodejs.org/en/docs/inspector
[Worker] Debugger attached.
[INFO 11:19:36 AM] [DEBUG] Debugging started
[INFO 11:19:43 AM] Running 1 file(s) with name pattern: ^\s?Class: CreateVEDTask Use case: Action is always discoverable action is available$
[Worker] Debugger listening on ws://127.0.0.1:9229/411c89e3-a316-42da-a4ee-aea9299cdacb
For help, see: https://nodejs.org/en/docs/inspector
[INFO 11:20:03 AM] [DEBUG] Starting debugging on localhost:43631
[INFO 11:20:03 AM] Running 1 file(s) with name pattern: ^\s?Class: CreateVEDTask Use case: Action is always discoverable action is available$
[Error 11:20:13 AM] [DEBUG] Debugging failed
```

### Version

0.10.0

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ffMathy** [comment]
Could use some help on where to insert log statements etc to help diagnose the issue on my repo, and therefore create a better reproduction.

I have no idea where to start.

**Comment by sheremet-va** [comment]
I am currently rewriting how debugging works (now spawns a separate Vitest instance) - let's see how stable it is.
