### ISSUE TITLE
Vitest VSCode fails to start without a Vitest config file

### ISSUE THREAD

**Issue by MangelMaxime** [vitest-dev/vscode#380]
### Describe the bug

Vitest VSCode fails to start without a Vitest config file.

I am pretty sure in the past it was able to start without a config file. Also I found https://github.com/vitest-dev/vscode/issues/348 mentioning the same issue and having a fix provided for it. So perhaps this is a regression.

### Reproduction

Open a repository without a Vitest config file.

### Output

```shell
[INFO 20:27:00] [v0.10.2] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[Error 20:27:00] [API] Failed to start Vitest: No vitest config files found
```

### Version

v0.10.2

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The extension expects either the config or a `script` in `package.json` that starts with `vitest`. Starting Vitest for any project seems excessive. What if you have vitest installed globally?

**Comment by MangelMaxime** [comment]
> What if you have vitest installed globally?

I would say this is a bad practice 😝 

More seriously, I understand the reason behind the decision you are describing. Perhaps the log can be changed to explain the situation / requirements or make these requirements documented somewhere?

If they are sorry I was not able to find it.
