### ISSUE TITLE
NVM support / Improve error message if node executable cannot be found

### ISSUE THREAD

**Issue by fehmer** [vitest-dev/vscode#381]
### Describe the bug

i'm using ubuntu linux and don't have a nodejs version installed globally but use `nvm`.  
On opening vscode there is a popup  `There was an error during Vitest startup.` and the output is this:
```
[INFO 1:06:28 PM] [v0.10.2] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 1:06:29 PM] [API] Running Vitest: v1.6.0 (vitest.config.js), v1.6.0 (vitest.config.js)
[Error 1:06:30 PM] [Error Error] spawn ENOTDIR
Error: spawn ENOTDIR
	at ChildProcess.spawn (node:internal/child_process:414:11)
	at spawn (node:child_process:799:9)
	at /home/user/.vscode/extensions/vitest.explorer-0.10.2/dist/extension.js:18:186
```

Best solution would be to use the default node version from nvm. If this is not possible improve the error message like `Cannot find node executable, set vitest.nodeExecutable configuration in your workspace or make sure node is installed at <expected-path>`

### Reproduction

- don't have node available globally
- open project with vitest in vscode

### Output

```shell
[INFO 1:06:28 PM] [v0.10.2] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 1:06:29 PM] [API] Running Vitest: v1.6.0 (vitest.config.js), v1.6.0 (vitest.config.js)
[Error 1:06:30 PM] [Error Error] spawn ENOTDIR
Error: spawn ENOTDIR
	at ChildProcess.spawn (node:internal/child_process:414:11)
	at spawn (node:child_process:799:9)
	at /home/user/.vscode/extensions/vitest.explorer-0.10.2/dist/extension.js:18:186
```

### Version

0.10.2

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by garyking** [comment]
Is this a new issue? I just installed the Vitest extension a few days ago, and I get this error every time I open a workspace in VSC. Is there a previous version of this extension I can roll back to for now, that doesn't have this issue?

**Comment by sheremet-va** [comment]
I also use `nvm` and it's working fine. The reproduction is not enough.

**Comment by fehmer** [comment]
Thanks for the reply. The issue was how I openened vscode. Opening it from a commandline works.
