### ISSUE TITLE
Disable warning when opening a project without Vitest

### ISSUE THREAD

**Issue by GRA0007** [vitest-dev/vscode#387]
### Describe the bug

Vitest shows a warning every time I open a project that uses Vite but does not use Vitest. https://github.com/vitest-dev/vscode/blob/49d8e8306dc46e68ffbb434a524bfc497646e306/src/api/pkg.ts#L41

I do not always use Vitest for various reasons, so I should be able to disable this warning with a setting like `vitest.warnIfNotInstalled = false`. A button on the warning like "Don't remind me again" could set this setting.

### Reproduction

Open any project that uses Vite but does not use Vitest

### Output

```shell
[INFO 13:50:07] [v0.10.7] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[Error 13:50:07] [API] Vitest not found for file:///Users/*/projects/*/vite.config.ts.
[Error 13:50:07] [API] Failed to start Vitest: No vitest config files found
```

### Version

0.10.7

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think it makes sense to have an option to do that, but we should ignore the warning automatically if there is no Vitest config/vitest in dependencies
