### ISSUE TITLE
Cannot find any test

### ISSUE THREAD

**Issue by vuggy17** [vitest-dev/vscode#389]
### Describe the bug

Vscode extension cannot find any test in the repository but the cli run fine.

### Reproduction

1. Open repo: https://github.com/vuggy17/idle2/tree/vite-ext-no-test
2. Install dependency: pnpm i
3. Run test (at the root folder): pnm test

Test run successfully but the extension cannot find any test

### Output

```shell
[INFO 12:01:42 PM] [API] Running Vitest: v1.6.0 (vitest.workspace.ts)
[INFO 12:01:42 PM] [API] Starting Vitest process with Node.js: /run/user/1000/fnm_multishells/8785_1716263711673/bin/node
[Worker] failed to load config from /home/vuggy17/workspace/idle2/vitest.config.ts
```

### Version

v0.10.7

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest cannot load config files that import raw TypeScript syntax. To bypass that, you are using `NODE_OPTIONS=\"--import tsx/esm\"` in your scripts.

You can add `NODE_OPTIONS: --import tsx/esm` to `vitest.nodeEnv` option to replicate that:

```jsonc
// settings.json
"vitest.nodeEnv": {
  "NODE_OPTIONS": "--import tsx/esm"
},
```
