### ISSUE TITLE
Unable to start extension

### ISSUE THREAD

**Issue by joyceli214** [vitest-dev/vscode#392]
### Describe the bug

Hi all, I am new to vite and just trying to get my tests running. However, when I tried to start the extension, it always resulted in the same error below

I am using below versions
vscode 1.89.0
vscode extension 0.10.7

I have tried
- uninstall and re-install extension
- kill and reopen vscode 
- restart computer
but none of them works

### Reproduction

https://github.com/vitest-dev/vitest/tree/main/examples/basic
I have tried with the example code from vitest and also could not start the extension (running npm test can run tests tho

### Output

```shell
[INFO 11:16:07 AM] [v0.10.7] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 11:16:10 AM] [API] Running Vitest: v1.6.0 (vite.config.ts)
[INFO 11:16:10 AM] [API] Starting Vitest process with Node.js: C:\Program Files (x86)\nodejs\node.EXE
[Error 11:16:18 AM] [Error Error] Vitest failed to start: 

r
Error: Vitest failed to start: 

r
    at ChildProcess.f (c:\Users\[my username]\.vscode\extensions\vitest.explorer-0.10.7\dist\extension.js:19:333)
    at ChildProcess.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Version

0.10.7

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nadihsu** [comment]
I encountered the same problem in vitest@0.10.7

**Comment by joyceli214** [comment]
I seemed to have gotten the extension running after upgrading node version from 16.15.1 to 20.13.1. Maybe could consider adding compatible node versions to the docs?

**Comment by sheremet-va** [comment]
Vitest requires Node 18+
