### ISSUE TITLE
Error during vitest startup since v0.6.0

### ISSUE THREAD

**Issue by programmer24601** [vitest-dev/vscode#396]
### Describe the bug

I'm getting a Vitest startup error on:
- Ubuntu 22.04.4 LTS
- Node 20.11.1
- npm 10.2.4
- asdf 0.14.0
- vitest 1.6.0
- vitest-vscode extension 10.0.7

Vitest itself runs fine, however, the extension falls over on startup. The latest version of the vitest extension to fully work for me is 0.4.1.

Experimenting with right-click -> Install Another Version...

 - `0.6.0 - 0.8.5` - no "Output" errors, no test run buttons, and the Testing pane contains: Vitest -> Resolving Vitest...
 - `0.8.6 - 0.10.7` - the below "Output" error, no test run buttons, and Testing pane is empty.

### Reproduction

At the moment I'm struggling to provide a reproduction of this. I've tried running the extension against the _basic_, _workspace_, _react_ official examples [here](https://github.com/vitest-dev/vitest/tree/main/examples), **which works** in all cases, but for my own current project (a two-package npm workspace) consistently gets this error. Is there a debug mode I can enable to get a stack trace to help with this?

If there's nothing to go on I can try and whittle down the project into something barebones I can share, but that will take some time.

### Output

```shell
[INFO 20:04:51] [v0.10.7] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 20:04:51] [API] Running Vitest: v1.6.0 (vitest.workspace.d.ts), v1.6.0 (vitest.workspace.js), v1.6.0 (vitest.workspace.ts)
[INFO 20:04:51] [API] Starting Vitest process with Node.js: /home/me/.asdf/shims/node
[Worker] ReferenceError: _default is not defined
[Error 20:04:52] [Error Error] Vitest process exited with code 1
Error: Vitest process exited with code 1
	at ChildProcess.d (/home/me/.vscode/extensions/vitest.explorer-0.10.7/dist/extension.js:21:170)
	at ChildProcess.emit (node:events:517:28)
	at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

### Version

0.10.7

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a problem with your config file somehow

**Comment by programmer24601** [comment]
Interesting. I'll try and reduce the project down to something I can share. In the mean time this is the repo structure:

```
.
├── package.json
├── package-lock.json
├── packages
│   ├── backend
│   │   ├── bin
│   │   │   └── index.ts
│   │   ├── functions
│   │   │   ├── function-1
│   │   │   │   ├── handler.test.ts
│   │   │   │   └── handler.ts
│   │   │   ├── function-2
│   │   │   │   ├── handler.test.ts
│   │   │   │   └── handler.ts
│   │   │   └── function-3
│   │   │       ├── handler.test.ts
│   │   │       └── handler.ts
│   │   ├── lib
│   │   │   ├── stack.test.ts
│   │   │   ├── stack.ts
│   │   ├── package.json
│   │   ├── tsconfig.json
│   │   └── vitest.config.ts
│   └── frontend
│       ├── index.html
│       ├── package.json
│       ├── src
│       │   ├── App.test.tsx
│       │   ├── App.tsx
│       │   ├── index.tsx
│       │   ├── setupTests.ts
│       │   └── vite-env.d.ts
│       ├── tsconfig.json
│       └── vite.config.ts
├── tsconfig.json
├── vitest.config.ts
└── vitest.workspace.ts
```

Vitest 1.6.0 is installed as a devDependency in each of the three package.json.

**Comment by sheremet-va** [comment]
It shouldn't load `vitest.workspace.d.ts` file - why do you have it? And where? I don't see it in your example. You can add it to `vitest.configSearchPatternExclude` in the vscode settings

**Comment by programmer24601** [comment]
You've solved it! tsc had transpiled vitest.workspace.ts into my outDir dist.
