### ISSUE TITLE
Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by longshihui** [vitest-dev/vscode#399]
### Describe the bug

When enable vitest vscode extension, rename dirname is not permitted.
This error always occurs on monorepos.
When project is not monorepos, rename is ok.

System: Windows 11 23H2
VSCode Version: 1.89.0

### Reproduction

1. `git clone https://github.com/longshihui/vitest-extension-rename-test.git`
2. open the project and run `pnpm install`
3. disable all vscode's extensions and restart vscode (ensure all extensions is disabled)
4. try rename `./packages/test-1` to `./packages/test-3`
5. only enable vitest extension
6. try rename `./packages/test-1` to `./packages/test-3`
7. get error

https://github.com/vitest-dev/vscode/assets/17525817/ba7be853-5242-47a9-961a-b0521f3e6e22

### Output

```shell
nothing.
```

### Version

v0.10.7(latest)

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sefabaser** [comment]
I have exactly the same problem. Happens with the same reproduction steps.

To fix this I did following steps:
- Installing system version of VSCode
- Giving all security accesses for the user for the folder
- Disabling all extensions (only disabling Vitest extension is working)

VScode: 1.92.1 (system setup)
Vitest extension: 1.0.7
OS: Windows 10
