### ISSUE TITLE
Run tests on save

### ISSUE THREAD

**Issue by bitsmakerde** [vitest-dev/vscode#4]
Hi,

is there an option to run all test from the file by save automatic like in the jest runner?

**Comment by zxch3n** [comment]
Hi. This is not available yet. It is in the plan.

Because in the current version the extension will rerun vitest every time. To enable vitest watch mode, we need to establish a connection to the vitest server. It requires more work.

**Comment by bitsmakerde** [comment]
Cool Thank you for the fast answer.
