### ISSUE TITLE
Coverage : Change color of line partially covered

### ISSUE THREAD

**Issue by chlbri** [vitest-dev/vscode#404]
### Clear and concise description of the problem

The color for lines covered and lines partially covered are the same

### Suggested solution

Choose color orange for lines partially covered
In this example, llines 108 and 110 are partially covered, but line 109 is not covered at all. So it's a bit confused

Image here : 

<img width="517" alt="Capture d’écran 2024-06-01 à 00 19 41" src="https://github.com/vitest-dev/vscode/assets/51156116/a20866b9-6e00-4b53-b27d-1303ac0b4d9e">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Coverage interface is controlled by the vscode itself. I tried to find setting to change the colors, but didn't find any. You can open an issue in vscode repository directly to ask for this feature.

**Comment by chlbri** [comment]
Ok, I see
