### ISSUE TITLE
Unexpected Token in JSON error when running tests

### ISSUE THREAD

**Issue by charliedavison** [vitest-dev/vscode#41]
**Describe the bug**
@testing-library/react: 13.1.1
vitest: 0.12.9

When running any test from the plugin the run fails with "SyntaxError: Unexpected token in JSON at position 52".

From the output It appears that the plugin is trying to write invalid JSON to a file and then read it back

```
JSON report written to /var/folders/nh/f9txjbr50mg66b89_51z2d2w0000gn/T/vitest-report-eqem9.json
JUNIT report written to /var/folders/nh/f9txjbr50mg66b89_51z2d2w0000gn/T/vitest-report-eqem9.json
Done in 1.09s.
Run test failed 
SyntaxError: Unexpected token 
                               in JSON at position 52
```

**Comment by charliedavison** [comment]
@zxch3n Great, thank you - any way around it for now or just need to wait for the change?

**Comment by zxch3n** [comment]
Does watch mode work for you?

**Comment by charliedavison** [comment]
In the CLI yes its fine

**Comment by zxch3n** [comment]
You can now use watch mode inside VS Code ![](https://camo.githubusercontent.com/749aa27e7b12f3d8bc0ad186659470fe4065fb2492c14494af868ce0ed70380c/68747470733a2f2f692e6962622e636f2f5952684a6a39662f53637265656e2d5265636f7264696e672d323032322d30352d32312d61742d32302d30392d32302e676966)

**Comment by zxch3n** [comment]
Does test running work on pre-release version now?
