### ISSUE TITLE
Testing tab does not show after installation

### ISSUE THREAD

**Issue by nddr** [vitest-dev/vscode#42]
**Describe the bug**
The 'Testing' tab, as shown in the extension screenshots, does not show after installation. Whether manually Enabled or not.

**To Reproduce**
1. Install Vitest extension

**Expected behavior**
'Testing' tab available like shown in screenshots.

**Screenshots**
<img width="1428" alt="Screen Shot 2022-05-25 at 11 30 17 PM" src="https://user-images.githubusercontent.com/1206846/170410314-6ff5842d-fe34-4d85-9a55-275f07013425.png">

**Environment**
- OS: macOS Monterey (12.0.1)
- VSCode version: 1.67.2 (May 2022)
- Vitest version: 0.12.9
- Vitest plugin version: 0.2.11 (Pre-release)

**Comment by zxch3n** [comment]
It will detect whether the current project is using vitest. If not, this extension will not be activated. Can you try reproducing this problem on https://github.com/zxch3n/vitest-ext-basic-example

**Comment by nddr** [comment]
Thank you @zxch3n. I got it working. A Vite config file is required for this to work.

**Comment by huzaifahj** [comment]
Yep, if `vite.config.ts` is not necessary for the extension to run then this is a bug that will cause friction in DX

**Comment by zxch3n** [comment]
@nddr @huzaifahj It uses these rules to detect whether the current project is Vitest environment to avoid conflict with projects using jest

https://github.com/vitest-dev/vscode/blob/ba12fee98adb3f23852902fd9cdf01fd18998a55/src/pure/isVitestEnv.ts#L7-L48

You can also enable this extension with the `vitest.enable` setting
