### ISSUE TITLE
No test output when debugging

### ISSUE THREAD

**Issue by seaders** [vitest-dev/vscode#423]
### Describe the bug

 I don't get any output stdout/stderr in the Test Output, and only the initial start line in Debug Console.

This issue is exactly the same as described for #137 and #117 which seems to have been fixed in https://github.com/vitest-dev/vscode/pull/228, but there's no evidence for output from a debug session / debugging an invidual test.

### Reproduction

1. Using the vitest extension, choose to debug any test file, or any indvidual test that has console.log or console.error
2. Test Output records nothing, and Debug Console only,
> /Users/seaders/.nvm/versions/node/v20.11.1/bin/node ./../../../../seaders/.vscode-insiders/extensions/vitest.explorer-0.12.3/dist/debug.js

https://github.com/vitest-dev/vscode/assets/955114/9c48ea29-7f8a-4acf-b9e6-f4b27f53a1a5

### Output

```shell
<empty>
```

### Version

0.12.3

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by seaders** [comment]
This can be overcome with a setting like below, but I'd still consider this a bug, or at the very least extremely obscure and something that needs better documentation somewhere.

```
import { defineConfig } from "vitest/config"

export default defineConfig(() => {
  return {
    test: {
      disableConsoleIntercept: !!process.env.VSCODE_INSPECTOR_OPTIONS
    }
  }
})

```

**Comment by sheremet-va** [comment]
There is a bigger problem. The "last" debug run is not reordered by VS Code at all (you can see in your Test Results the last debug run is not in a finished state). I don't know why it is so.

**Comment by sheremet-va** [comment]
This should be fixed in 0.12.4.

**Comment by seaders** [comment]
I'd contend that that fix is just as bad, because the console output doesn't come until the end of the test.  Consider a regular debugging session like the one in the video, and this,

<img width="1245" alt="image" src="https://github.com/vitest-dev/vscode/assets/955114/aa5c1fff-4aae-48ca-b282-262f26055e6f">

When you're in a breakpoint after some print statements, you want to be able to see those print statements.  Personally, I'd prefer the behaviour that occurs when you set `disableConsoleIntercept`,

<img width="1230" alt="image" src="https://github.com/vitest-dev/vscode/assets/955114/1a9fb882-c68d-4e54-8ba3-a6b214434ce0">

Because then you see all the output prior to that point when in a breakpoint.

**Comment by sheremet-va** [comment]
Then it's a good thing that `disableConsoleIntercept` exists, isn't it 😄 

Use it if you prefer it that way.  There is nothing that can be done in the extension because the console is intercepted by Vitest and the breakpoint makes it impossible to send the data in time.

**Comment by seaders** [comment]
I get that, I really do.  Any chance of updates to docs?  Or, if you point me to where to update, I'd be happy to contribute to a few sentences.

Overall, I felt there's a lack of ... love/tlc to this specifically IMO fantastic feature of vitest with VS Code.  I found that most of the docs focus on testing the "whole" unit of a project, the way that you'd run vitest cli, rather than this kind of situation, using testing during development, writing code, test, debug, tinker, test and debug again.  The docs barely even make mention of context menu "Debug Test", which I find an incredibly useful and powerful tool, but then got incredibly frustrated with the situation I then found myself in with no output.

I then only found reference to `disableConsoleIntercept` deep in a closed github issue, or SO thread.  I can't even find where I found it in my history.

**Comment by sheremet-va** [comment]
Looks like `disableConsoleIntercept` is not documented in Vitest docs. You can open a PR there.

>  I found that most of the docs focus on testing the "whole" unit of a project, the way that you'd run vitest cli

I do not have a lot of time working on every feature in parallel to also write comprehensive documentation for everything. There is however an open issue to add more documentation: https://github.com/vitest-dev/vscode/issues/338 (inspired by jest extension readme: https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest)

Feel free to open a PR with instructions on how to properly run those types of tests.
