### ISSUE TITLE
Vitest failes to start in vscode >=1.90 when using Yarn PnP

### ISSUE THREAD

**Issue by fmal** [vitest-dev/vscode#426]
### Describe the bug

With latest VSCode (version 1.90.2) the extension fails to start Vitest in a project setup with Yarn PnP:

<img width="813" alt="SCR-20240630-shux" src="https://github.com/vitest-dev/vscode/assets/927591/01194e2d-d4f2-4d49-8b39-e15fb9e80f41">
<img width="313" alt="SCR-20240630-shxf" src="https://github.com/vitest-dev/vscode/assets/927591/0ef2a54d-3b4d-4ed0-ac0e-926b02a92891">

Downgrading VSCode to version 1.89.1 results in Vitest process being successfully created:

<img width="777" alt="SCR-20240630-sfac" src="https://github.com/vitest-dev/vscode/assets/927591/24a23a92-4e65-41e4-8b01-2d6b877b2482">
<img width="269" alt="SCR-20240630-sffl" src="https://github.com/vitest-dev/vscode/assets/927591/176bb43d-98fe-4499-a381-f98c74592588">

I suspect it has to do with Electron upgrade in latest VSCode release that comes bundled with Node.js 20.

### Reproduction

https://github.com/Nithanim-Work/vitest-reproducer (reusing minimal example from https://github.com/vitest-dev/vscode/issues/416)

### Output

```shell
[INFO 21:10:03] [v0.12.4] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 21:10:04] [API] Running Vitest vpnp (web/vitest.config.ts) with Node.js: /Users/fima/.asdf/shims/node
[Error 21:10:05] [Error Error] Vitest failed to start: 

y
Error: Vitest failed to start: 

y
	at ChildProcess.f (/Users/fima/.vscode/extensions/vitest.explorer-0.12.4/dist/extension.js:18:5392)
	at ChildProcess.emit (node:events:514:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Version

0.12.4

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by niuyuping** [comment]
same

**Comment by niuyuping** [comment]
i got same issue

**Comment by niuyuping** [comment]
Upate:

**Comment by sheremet-va** [comment]
There is a small patch in 1.0.7. Please let me know if it works for you.

**Comment by niuyuping** [comment]
![image](https://github.com/user-attachments/assets/64db5d4a-e157-48d3-8f5e-6f11015f5015)
A new error message after update to 1.0.7

**Comment by niuyuping** [comment]
I checked the .yarn folder in my project, the snapshot is below

![image](https://github.com/user-attachments/assets/20370600-2df9-42ce-9c19-75c3c2712222)

I use yarn in pnp mode.

**Comment by pavitra-infocusp** [comment]
Same thing with PNPM

```
[INFO 13:29:34] [v1.0.7] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 13:29:34] [API] Running Vitest v2.0.5 (Test-Extension/vitest.config.ts) with Node.js: /snap/bin/node
[Error 13:29:34] [Error Error] Vitest process exited with code null
Error: Vitest process exited with code null
	at ChildProcess.p (/home/pavitra/.vscode/extensions/vitest.explorer-1.0.7/dist/extension.js:19:177)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess.emit (node:domain:488:12)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by L2HYUNN** [comment]
same issue with yarn v4.4 PnP

![image](https://github.com/user-attachments/assets/fb642703-f02b-4e92-84bf-5c1f75a6850e)

**Comment by fmal** [comment]
@sheremet-va thanks for taking time to address this, after updating to latest version i get a different error on startup that is a bit similar to what others are reporting (thou it fails at loading different dependency):

<img width="776" alt="SCR-20240820-bmbm" src="https://github.com/user-attachments/assets/568f267a-546d-4932-8b3a-0a4be8ee469b">


It should be reproducible using the repo at https://github.com/Nithanim-Work/vitest-reproducer

**Comment by fmal** [comment]
@sheremet-va thanks, unfortunately with the minimal reproduction repo (https://github.com/Nithanim-Work/vitest-reproducer) extension still fails to start. I tried on 2 different machines and get the same error:
<img width="1234" alt="SCR-20240820-nvvh" src="https://github.com/user-attachments/assets/8041648c-2d27-4c31-8dd6-e53f71ed1ab6">

**Comment by sheremet-va** [comment]
I see now why it happens. Does the extension work for you if you have Vitest installed globally?

**Comment by fmal** [comment]
Not sure how to test that, `yarn` > 1 doesn't provide a way to install packages globally, see https://yarnpkg.com/migration/guide#use-yarn-dlx-instead-of-yarn-global. I tried installing `vitest` globally with legacy yarn using `yarn global` command as well as `npm install vitest -g`, but that didn't change anything.

**Comment by ParkerRobinson** [comment]
I'm also able to repro and have tried installing the extension globally, no luck.

You can get past this error and have extension make it past startup by installing whatever package it says is missing in the directory its looking for it... but you'll then run into issues when you try to run any test via the UI as each test's packages are going to be missing.

**Comment by jordanpg** [comment]
After messing around for a while, I managed to figure out a workaround. The pnp loader doesn't seem to want to resolve modules the way the worker hopes to be able to (i.e. it doesn't seem to check the workspace at all). Not really sure if this is an issue with yarn or if the extension is meant to be doing something different (like using the plugin API or something)  
  
Unpacking vitest and pointing directly to it fixes the `vitest/node` import as @viell-dev says above, but the extension seems to skip adding the pnp hooks when you specify `vitestPackagePath,` so vitest's dependencies would also fail to resolve. This can be worked around through the `NODE_OPTIONS` environment variable; though the extension could be updated to skip this requirement

1. Run `yarn unplug vitest` (don't think -R is needed)
2. Configure `vitest.vitestPackagePath` to point to the unpacked `package.json`
```json
"vitest.vitestPackagePath": ".yarn/unplugged/vitest-virtual-b853d33a81/node_modules/vitest/package.json"
```
3. Configure `vitest.nodeEnv` to set the `NODE_OPTIONS` env. var similar to the following:
```json
"vitest.nodeEnv": {
    "NODE_OPTIONS": "--require C:\\your\\path\\to\\.pnp.cjs --experimental-loader file:///C:/your/path/to/.pnp.loader.mjs",
},
```

i imagine there's a way to configure this so that you don't have to hard-set the paths but this works for me

**Comment by niuyuping** [comment]
> After messing around for a while, I managed to figure out a workaround. The pnp loader doesn't seem to want to resolve modules the way the worker hopes to be able to (i.e. it doesn't seem to check the workspace at all unless the importer or the imported script are in the workspace). Not really sure if this is an issue with yarn or if the extension is meant to be doing something different (like using the plugin API or something)
> 
> Unpacking vitest and pointing directly to it fixes the `vitest/node` import as @viell-dev says above, but the extension seems to skip adding the pnp hooks when you specify `vitestPackagePath,` so vitest's dependencies would also fail to resolve. This can be worked around through the `NODE_OPTIONS` environment variable; though the extension could be updated to skip this requirement
> 
> 1. Run `yarn unplug vitest` (don't think -R is needed)
> 2. Configure `vitest.vitestPackagePath` to point to the unpacked `package.json` (this may be different for you)
> 
> ```json
> "vitest.vitestPackagePath": ".yarn/unplugged/vitest-virtual-b853d33a81/node_modules/vitest/package.json"
> ```
> 
> 3. Configure `vitest.nodeEnv` to set the `NODE_OPTIONS` env. var similar to the following:
> 
> ```json
> "vitest.nodeEnv": {
>     "NODE_OPTIONS": "--require C:\\your\\path\\to\\.pnp.cjs --experimental-loader file:///C:/your/path/to/.pnp.loader.mjs",
> },
> ```
> 
> i imagine there's a way to configure this so that you don't have to hard-set the paths but this works for me

Thanks~~that works for me. The command yarn unplug -R vitest works, but without the -R parameter, it does not. Additionally, in Yarn versions 4 and above, you need to add pnpEnableEsmLoader: true to your yarnrc.yml file; otherwise, the .pnp.cjs and .pnp.loader.mjs files will not be found.

**Comment by dawsonbooth** [comment]
I may be missing something, but I'm unfortunately still getting a startup crash with Yarn PnP on v1.2.10:

```
[INFO 1:02:13 PM] [v1.2.10] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 1:02:14 PM] [API] Running Vitest vpnp (ui/vite.config.ts) with Node.js: ~/Library/Caches/fnm_multishells/3213_1727368426358/bin/node 
[Error 1:02:14 PM] [Error Error] Vitest failed to start: 
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected array buffer, or typed array to be returned for the "source" from the "transformSource" function but got undefined.
    at assertBufferSource (node:internal/modules/esm/translators:104:9)
    at stringify (node:internal/modules/esm/translators:119:3)
    at createCJSModuleWrap (node:internal/modules/esm/translators:279:12)
    at ModuleLoader.commonjsStrategy (node:internal/modules/esm/translators:358:10)
Error: Vitest failed to start: 
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected array buffer, or typed array to be returned for the "source" from the "transformSource" function but got undefined.
    at assertBufferSource (node:internal/modules/esm/translators:104:9)
    at stringify (node:internal/modules/esm/translators:119:3)
    at createCJSModuleWrap (node:internal/modules/esm/translators:279:12)
    at ModuleLoader.commonjsStrategy (node:internal/modules/esm/translators:358:10)
	at ChildProcess.f (~/.vscode/extensions/vitest.explorer-1.2.10/dist/extension.js:19:5641)
	at ChildProcess.emit (node:events:519:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by sheremet-va** [comment]
This is a different error that was never reported. I cannot help you unless you provide any kind of reproduction. Adding +1 will not help fix the issue.

**Comment by TehPers** [comment]
Node.js: v20.17.0 (with `corepack enable`)

1. `yarn create vite` to make a project. (`yarn@3.5.0` is installed, as is `vite@5.4.1`)
2. `yarn dlx @yarnpkg/sdks vscode` to setup editor SDKs
3. `yarn add -D vitest` (installs `vitest@2.1.1`)
4. Add a `src/example.test.ts` with a very simple unit test. Verify it runs with `yarn run vitest`.
5. Install v1.2.10 of the Vitest extension.

```
[INFO 12:38:43 PM] [v1.2.10] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[Error 12:38:43 PM] [Error Error] Cannot find module 'vitest/node'
Require stack:
- E:\Dev\Random\blah
Error: Cannot find module 'vitest/node'
Require stack:
- E:\Dev\Random\blah
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at Function.i._resolveFilename (node:electron/js2c/utility_init:2:13739)
    at callNativeResolution (e:\Dev\Random\blah\.pnp.cjs:11948:30)
    at resolveToUnqualified (e:\Dev\Random\blah\.pnp.cjs:12106:24)
    at resolveRequest (e:\Dev\Random\blah\.pnp.cjs:12355:31)
    at Object.resolveRequest (e:\Dev\Random\blah\.pnp.cjs:12418:26)
    at zr (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:24:651)
    at c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:24:3210
    at Array.forEach (<anonymous>)
    at Lg (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:24:3174)
    at Qc (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:24:3075)
    at Bn._defineTestProfiles (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:25:2126)
    at Bn.defineTestProfiles (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:25:2028)
    at Bn.activate (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:25:6333)
    at lv (c:\Users\tehpe\.vscode\extensions\vitest.explorer-1.2.10\dist\extension.js:25:1053)
    at m.n (c:\Users\tehpe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6409)
    at m (c:\Users\tehpe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6372)
    at m.l (c:\Users\tehpe\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5829)
```

**Comment by sheremet-va** [comment]
@TehPers please, check if v1.2.11 fixes it for you.

**Comment by dawsonbooth** [comment]
@sheremet-va v1.2.11 fixed the issue I was seeing. Thank you!

**Comment by TehPers** [comment]
> @TehPers please, check if v1.2.11 fixes it for you.

The latest version is working for me now. Thank you!
