### ISSUE TITLE
Open VSX Registry (VSCodium) forcing outdated version (1.0.0-beta.X)

### ISSUE THREAD

**Issue by flx-sta** [vitest-dev/vscode#427]
### Describe the bug

When installing the extension in VSCodum via the VSX Registry it install the wrong version (1.0.0-beta.X).
Even though those version were released month ago

I'm able to use it by just manually selecting the correct version to install but it's a real inconvenience 
<img width="487" alt="image" src="https://github.com/vitest-dev/vscode/assets/50131232/4a690764-695b-4840-b30b-d75225c4bb53">

I have a parallel report on discord of this:
https://discord.com/channels/917386801235247114/1257899109311057990

### Reproduction

1. Install VSCodium
2. Start it
3. Install vitest extension
4. Check the version

### Output

```shell
[INFO 8:17:07 PM] Trying to get vitest version from /Users/<user>/projects/<git-repo>/node_modules/.bin/vitest -v...
[INFO 8:17:07 PM] Running command in directory: /Users/<user>/projects/<git-repo>
[INFO 8:17:07 PM] vitest/1.5.2 darwin-arm64 node-v20.13.0

[INFO 8:17:07 PM] Vitest Workspace [<git-repo>]: Vitest version = 1.5.2
[INFO 8:17:07 PM] pure/WS Close
[INFO 8:17:07 PM] RECONNECT
[INFO 8:17:41 PM] pure/WS Close
[INFO 8:17:41 PM] RECONNECT
[INFO 8:17:41 PM] pure/WS Close
[INFO 8:17:42 PM] RECONNECT
[INFO 8:17:42 PM] pure/WS Close
[INFO 8:17:42 PM] RECONNECT
[INFO 8:17:42 PM] pure/WS Close
[INFO 8:17:43 PM] RECONNECT
[INFO 8:17:43 PM] pure/WS Close
[INFO 8:17:43 PM] RECONNECT
[INFO 8:17:43 PM] pure/WS Close
[INFO 8:17:44 PM] RECONNECT
[INFO 8:17:44 PM] pure/WS Close
[INFO 8:17:44 PM] RECONNECT
[INFO 8:17:44 PM] pure/WS Close
[INFO 8:17:45 PM] RECONNECT
[INFO 8:17:45 PM] pure/WS Close
[INFO 8:17:45 PM] RECONNECT
[INFO 8:17:45 PM] pure/WS Close
[INFO 8:17:46 PM] RECONNECT
[INFO 8:17:46 PM] pure/WS Close
[INFO 8:17:46 PM] RECONNECT
[INFO 8:17:46 PM] pure/WS Close
[INFO 8:17:47 PM] RECONNECT
[INFO 8:17:47 PM] pure/WS Close
[INFO 8:17:47 PM] RECONNECT
[INFO 8:17:47 PM] pure/WS Close
[INFO 8:17:48 PM] RECONNECT
[INFO 8:17:48 PM] pure/WS Close
[INFO 8:17:48 PM] RECONNECT
[INFO 8:17:48 PM] pure/WS Close
[INFO 8:17:49 PM] RECONNECT
[INFO 8:17:49 PM] pure/WS Close
[INFO 8:17:49 PM] RECONNECT
[INFO 8:17:49 PM] pure/WS Close
[INFO 8:17:50 PM] RECONNECT
[INFO 8:17:50 PM] pure/WS Close
```

### Version

1.0.0-beta.1

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yeah, Open VSX doesn't support tagging - we can't override the latest version until we publish v1.

**Comment by flx-sta** [comment]
@sheremet-va thanks for the quick response. That's too bad.. Can't those version be removed from Open VSX or am I thinking to simple?

**Comment by sheremet-va** [comment]
I didn't find a way to remove them using the API, it's pretty limited

**Comment by flx-sta** [comment]
@sheremet-va Alright. How annoying..
Well I've left a 5 ⭐ review referencing this issue and explaining the situation. Hope this helps some ppl.
MAYBE adding an info the readme would help too?

**Comment by sheremet-va** [comment]
I am planning to release v1 pretty with the browser support soon, so I don't think it will be a problem for long.

**Comment by flx-sta** [comment]
@sheremet-va sounds good.
Can i close this issue or do you want me to keep it open till then?

**Comment by sheremet-va** [comment]
Should be fixed now
