### ISSUE TITLE
Debugging test regression after 0.10.7

### ISSUE THREAD

**Issue by vchirikov** [vitest-dev/vscode#434]
### Describe the bug

Between [0.10.7..0.12.0](https://github.com/vitest-dev/vscode/compare/v0.10.7..v0.12.0#diff-89c116a914ae3d3e7573d96c9462cfa90425215062ea9ec3299e8d6e45170832L22) `process.chdir()` was removed, which causes vitest start problem if you're use vscode workspace folder != folder there vites.config.ts present. (vitest failed with exitcode 1)

### Reproduction

![bug](https://github.com/vitest-dev/vscode/assets/40987940/6fde5248-7677-4142-acb7-985a734aa0e8)

### Output

```shell
--
```

### Version

0.12.4

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you not assume when the bug is, but rather describe the issue itself. `process.chdir` is removed because `child_process` is initiated with correct `cwd` now and has nothing to do with debugger.

**Comment by sheremet-va** [comment]
Debugger config wasn't using project CWD: https://github.com/vitest-dev/vscode/commit/3bfe794850cf4c9f7e3d571f00d5f4d052cb55ca

**Comment by vchirikov** [comment]
@sheremet-va thanks for fast fix
