### ISSUE TITLE
Vitest plugin fails to run tests in a monorepo with app-specific config

### ISSUE THREAD

**Issue by shmichael** [vitest-dev/vscode#446]
### Describe the bug

In our monorepo we have:
* `/apps` - for micro services each with their own node-config setup
* `/packages` - for reusable packages between apps.
 
In the command line we run tests either globally (using turbo) or in specific apps (using `pnpm -F appname test`) - both work well.

However, the vitest vscode plugin is only able to run tests in the `/packages` subdir. The tests under `/apps` fail to run because vitest seems to expect the config file for the apps to be under the root:
```
WARNING: No configurations found in configuration directory: <repo root>/config
```
This is obviously not possible since different apps have different configs, which might overlap, and anyway we're interested in keeping app-specific configs under the relevant app.

Is there a fix that allows each app's test to correctly pull its relevant config?

### Reproduction

Our repo is private

### Output

```shell
This output replaces the root repo dir with <root> and the on disk path to root with <path>

[INFO 09:24:47] [v1.0.6] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 09:24:47] [API] Using user workspace config: <path>/vitest.workspace.ts
[INFO 09:24:48] [API] Running Vitest v1.6.0 (<root>/vitest.workspace.ts) with Node.js: <pnpm_path>
[INFO 09:24:48] [API] Vitest v1.6.0 (<root>/vitest.workspace.ts) process 34207 created
[INFO 09:30:21] Running 1 file(s): apps
[Worker] WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:<path>/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
```

### Version

1.0.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> vitest seems to expect the config file for the apps to be under the root

This is not accurate.

> Our repo is private

I cannot help you if you can't provide _any_ sort of reproduction.

**Comment by anantharam** [comment]
I have added a minimal reproduction here : https://stackblitz.com/edit/vitest-dev-vitest-hkrvhg

You can see in this screenshot that the same test fails in vscode test and the test is passing when run from terminal : 
![image](https://github.com/user-attachments/assets/65687e50-04a0-4349-ae5c-19a2c9b38bcf)
