### ISSUE TITLE
Failing test highlight is on wrong line

### ISSUE THREAD

**Issue by douglashellowell** [vitest-dev/vscode#45]
**Describe the bug**
When running tests using the test runner the red bar highlighting the test title is 6 lines too high

**To Reproduce**
write tests - run tests using  VSCode / extensions test runner - have one test fail

**Expected behavior**
the red bar to highlight the failing tests description

**Screenshots**

<img width="658" alt="Screenshot 2022-06-08 at 18 12 29" src="https://user-images.githubusercontent.com/53038423/172676944-d75ab7a6-b344-41fa-9240-1514ebef8a9b.png">

> p.s this screetshot comes midway through a little refactor - don't mind the tests that don't make sense 😅 

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS
- VSCode version: `1.67.2`
- Vitest version: `^0.14.1`
- Vitest plugin version: `v0.2.12`

**Additional context**

* typescript
* is testing a utility function for a svelte app

**Comment by douglashellowell** [comment]
sorry for the slow reply - yes it was in watch mode!

**Comment by teetow** [comment]
Here's a couple of screenshots that might be helpful. It looks like the injected comment is slowly drifting from its correct line:
![image](https://user-images.githubusercontent.com/183582/180020811-5c2f10f3-48b7-4cc5-8903-92de89869321.png)

Packing the lines as tightly as possible throws it off in the other direction:
![image](https://user-images.githubusercontent.com/183582/180022389-b491d38d-e5fa-49d7-8fe5-8f80eaa33cf1.png)

Meanwhile, the gutter indicator is all like ¯\\_(ツ)_/¯

Very interesting bug, hope this helps.
