### ISSUE TITLE
Cannot stop "watch"

### ISSUE THREAD

**Issue by birgersp** [vitest-dev/vscode#46]
**Describe the bug**
Title. I clicked "Run Tests (Watch Mode)" but I can't find any way to stop it. I had to restart vscode.

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Start it
2. Try to stop it

**Comment by zxch3n** [comment]
There is a `Vitest: Toggle Watch Mode` command. And you can stop the watch mode by clicking the vitest status bar button. Do you have suggestions for a new stop entry?

**Comment by birgersp** [comment]
Thanks for that info!

I started it by clicking here:

![image](https://user-images.githubusercontent.com/5260237/172906702-33db31a0-43ad-4094-832e-87d41042e74c.png)

And I couldn't see a "stop" button anywhere. Searching for the command is something I should have thought of.

Ideally there could be a "stop" button where the start button is (ref. my image).

**Comment by khattaksd** [comment]
I would love to see  a `Stop Tests (Watch Mode)`
