### ISSUE TITLE
Logs should go to Output pane channel rather than dev console

### ISSUE THREAD

**Issue by ulugbekna** [vitest-dev/vscode#460]
### Clear and concise description of the problem

It's a best practice for vscode extensions that the logs go to the Output pane channel rather than dev tools console because dev console contains lots of info and errors unrelated to the extension while the output channel is dedicated to the extension. It's a lot user friendlier for extension users to consume. Using log infra also allows filtering logs by log-level (eg trace, debug, info, etc) 

### Suggested solution

It's preferable to use https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel. 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vscode/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vscode/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What do you mean? This is how we already log: https://github.com/vitest-dev/vscode/blob/main/src/log.ts

**Comment by ulugbekna** [comment]
Thank you for prompt reply @sheremet-va ! 

I see these logs in dev console: 



![Image](https://github.com/user-attachments/assets/cbd7439d-c1f4-4f61-8733-488d5d31723a)

**Comment by sheremet-va** [comment]
Maybe we should `console.log` them only for dev builds then. These logs are duplicated both in Output and Debug.
