### ISSUE TITLE
Update snapshots

### ISSUE THREAD

**Issue by ilteoood** [vitest-dev/vscode#463]
### Describe the bug

In the text explorer, update snapshot appears twice.
The first one does nothing, while the second one correctly complete the action
![image](https://github.com/user-attachments/assets/eea4f771-41fc-438e-893f-d2bd16efbd4a)

### Reproduction

Just right click on a test

### Output

```shell
Clicking on the first `Update Snapshot`, nothing happens
```

### Version

v1.2.1

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Output

This is not the output

> Just right click on a test

This is not a reproduction

I only have a single one. Maybe you have other test runners extensions installed?

<img width="343" alt="Screenshot 2024-09-06 at 13 48 34" src="https://github.com/user-attachments/assets/d2c30bfb-4229-4957-9a20-f5f177422758">

**Comment by ilteoood** [comment]
@sheremet-va, I know that's not an output. But literally: nothing happens in the vitest's extension logs when I click that button.
Seems to be related to `https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest`: if I disable it, it goes away.
It's a curious behaviour, isn't it? The run test functionality is not colliding, but the update snapshot is 🤔

**Comment by sheremet-va** [comment]
Vitest should no longer show "Update snapshot" button in other test controllers (e.g., jest). Other controllers need to add the condition themselves like here: https://github.com/vitest-dev/vscode/commit/cbbb746210323c2e1871324d5b9f558bb7275d6a
