### ISSUE TITLE
Context buttons at wrong line when returning Promise from test

### ISSUE THREAD

**Issue by rafagsiqueira** [vitest-dev/vscode#464]
### Describe the bug
![Screenshot 2024-09-05 at 8 59 05 AM](https://github.com/user-attachments/assets/b75dcabd-b6fc-423e-a70c-69a46eeb4495)

As shown on the screenshot, the context button (for running the test from the test file) and error messages (from failed expects) is shown at the wrong line, whenever a test returns a Promise.

### Reproduction

Test case with the following syntax:
```
it('just a test', ({expect}) => new Promise<void>((resolve, reject) => {
 resolve();
}
```

### Output

```shell
[8:58:59 AM] Marking "just an asynchronous test" as running
[8:59:00 AM] Marking "just an asynchronous test" as passed
[8:59:00 AM] Ending test run projects/etips-utils/search/src/pochettes.service.spec.ts
```

### Version

v1.2.1

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rafagsiqueira** [comment]
Thank you for your answer @andersonsilva87. Would you care to explain the solution instead of sending a zip file? Unfortunately it looks too suspicious.

**Comment by sheremet-va** [comment]
> Thank you for your answer @andersonsilva87. Would you care to explain the solution instead of sending a zip file? Unfortunately it looks too suspicious.

It is a malicious bot. Please, do not install anything from there.

**Comment by sheremet-va** [comment]
> Output

This is not the full output. Please, provide the full output.

**Comment by rafagsiqueira** [comment]
@sheremet-va I realized the minimal repro I sent is not enough. I am trying to reproduce the issue with a new test spec, but couldn't find yet what triggers the unexpected behavior. Will revert back when I find out.

**Comment by rafagsiqueira** [comment]
@sheremet-va it apparently happens when I add this to the beginning of my test files:
```
/**
 * @vitest-environment jsdom
 * @vitest-environment-options { "url": "http://localhost" }
 */
```
Is there another way to set the environment option url?

**Comment by rafagsiqueira** [comment]
Adding this to vitest.config and removing the annotations from the test files works:
```
test: {
      environmentOptions: {
            jsdom: {
                url: 'http://localhost'
            }
        }
}
```

**Comment by rafagsiqueira** [comment]
I thought removing annotations from test files fixed it, but I can still see instances where the context buttons are in the wrong line of the tests. Still trying to understand what triggers the bug.

**Comment by sheremet-va** [comment]
Maybe you are using a plugin that produces incorrect source maps. Do you see the error column and line correctly when the test fails in the terminal?

**Comment by rafagsiqueira** [comment]
@sheremet-va It's an angular application, and it uses @analogjs/vitest-angular:test as the builder.
```
"test": {
          "builder": "@analogjs/vitest-angular:test",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "config": "vitest.config.mjs"
          }
        },
```
Do you think that might be the culprit?
The following test seems to be a minimal reproduction:
```
import { describe, it } from 'vitest';

describe('ActionsService', () => {

  it('should be created', ({ expect }) => {
    expect(true).toBeTruthy();
  });

  // it('should load action', ({ expect }) => new Promise<void>((resolve, reject) => {
  //   const actionId = '932B0131-29BD-50C0-BB95-0011A8614E71';
  //   const actionGQL = TestBed.inject(ActionGQL);
  // }));

  it('should fail', ({ expect }) => new Promise<void>((resolve, reject) => {
    expect(false).toBeTruthy();
  }));
});
```
Adding comments to the test seems to do the trick.

**Comment by rafagsiqueira** [comment]
@sheremet-va found an open issue in their project: https://github.com/analogjs/analog/issues/1211
