### ISSUE TITLE
Nested package structure

### ISSUE THREAD

**Issue by timges** [vitest-dev/vscode#49]
**Is your feature request related to a problem? Please describe.**

When you have a nested pkg structure like root/frontend/... the extension still tries to find your package.json at root/package.json instead of root/frontend/package.json

**Describe the solution you'd like**
Make the root path customizable

**Comment by Inviz** [comment]
Having the same issue. Couldn't solve it. Some `cwd` option would really help.

**Comment by ngirardin** [comment]
Hi guys, that should be solved with the latest version (v0.2.39).

Could you give it a try?

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
