### ISSUE TITLE
1.4.0 throws cannot find module 'ws' when debugging a test

### ISSUE THREAD

**Issue by gunters63** [vitest-dev/vscode#492]
### Describe the bug

With the new 1.4.0 version I cannot debug tests anymore, I get the following error in the debug console:

![image](https://github.com/user-attachments/assets/7374bc50-7c43-44a4-815e-733bb2d68326)

The previous version 1.2.20 does work

### Reproduction

Debugging any test throws this error

### Output

```shell
[INFO 3:24:39 PM] [v1.4.0] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 3:24:40 PM] [API] Running Vitest v2.1.1 (EnsoUi/vitest.workspace.ts) with Node.js@v20.14.0: /home/gunter/.nvm/versions/node/v20.14.0/bin/node 
[INFO 3:24:41 PM] [API] Vitest v2.1.1 (EnsoUi/vitest.workspace.ts) child process 466984 created
[INFO 3:24:41 PM] [API] Collecting tests: apps/web-server/src/plugins/admin/app/.server/authStrategies/fixedAccount/login.spec.ts
[3:24:41 PM] Not starting the runner because tests are being collected for apps/web-server/src/plugins/admin/app/.server/authStrategies/fixedAccount/login.spec.ts
[3:24:41 PM] There is no test run for "[@enso/web-server] login.spec.ts"
[3:24:41 PM] No test run to finish for apps/web-server/src/plugins/admin/app/.server/authStrategies/fixedAccount/login.spec.ts
[3:24:42 PM] [VSCODE] File changed: node_modules/.vite/vitest/results.json
[INFO 3:24:44 PM] [DEBUG] Starting debugging session /home/gunter/.nvm/versions/node/v20.14.0/bin/node
[INFO 3:24:45 PM] [DEBUG] Debugging started
```

### Version

1.4.0

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Thank you for the report! This should be fixed by https://github.com/vitest-dev/vscode/commit/14eedaab5ab491b508dd153bb50cab9a3fea1b04
