### ISSUE TITLE
Console.log output is truncated

### ISSUE THREAD

**Issue by mbtools** [vitest-dev/vscode#504]
### Describe the bug

The extension captures the console log and displays it in the output window. However, messages are often (not quite always) truncated. Here's a test which I ran 3 times:

```ts
test('vitest console log test', () => {
  console.log('message 1');
  console.log('message 2');
  console.log('message 3');
});
```

![image](https://github.com/user-attachments/assets/687bd2ba-c2ee-4dcf-8362-22646ce77448)

Maybe this is not right:

https://github.com/vitest-dev/vscode/blob/becf8269f703e1e7d947f3180609280cb5e56a43/src/log.ts#L9-L10

### Suggestion

My wish would be to get the console log into a separate output window, call it "Vitest Console Log" 🙏 😃 

PS: Other extensions like Copilot use multiple output windows, too. 

### Reproduction

- Create and run the test 3x
- Check output

VSCode: 1.94.2
OS: Windows_NT x64 10.0.19045
Node: 20.15.1
Npm: 10.8.2

### Output

```shell
[INFO 10:19:45 AM] Running 1 file(s) with name pattern: ^\s?vitest console log test$
[INFO 10:19:46 AM] [Worker] message 
[INFO 10:19:46 AM] [Worker] message 2
message 
[INFO 10:19:49 AM] Running 1 file(s) with name pattern: ^\s?vitest console log test$
[INFO 10:19:50 AM] [Worker] message 
[INFO 10:19:50 AM] [Worker] message 
[INFO 10:19:50 AM] [Worker] message 
[INFO 10:19:53 AM] Running 1 file(s) with name pattern: ^\s?vitest console log test$
[INFO 10:19:54 AM] [Worker] message 1
message 2
message
```

### Version

v1.6.0

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The "Output" tab is an internal logging tab; it's not meant for public usage. The extension prints all logs to the "Test Results" tab already, so there is no need to duplicate it yet again:

<img width="1136" alt="Screenshot 2024-10-17 at 16 48 16" src="https://github.com/user-attachments/assets/19976094-4eb2-43bd-9e5c-a96557641b69">

But the fact that it's truncated in the output tab is a bug.

**Comment by mbtools** [comment]
My Test Results tab wasn't working. It does now after Code restart 👍 Thanks
