### ISSUE TITLE
Test file cannot be found if the test file or the directory contains uppercase characters.

### ISSUE THREAD

**Issue by jtamyrc** [vitest-dev/vscode#54]
**Describe the bug**
Test file cannot be found if the test file or the directory contains uppercase characters.

For example,
If the test file located in Category directory, such as `/app/src/components/Category/CategoryContainer.test.js`, the test file cannot be found.

**To Reproduce**
Click the test button if the test file or the directory contains uppercase characters.

**Screenshots**
test file and directory setup
![image](https://user-images.githubusercontent.com/98812101/178464104-62582312-0ad8-43d6-8860-a3c3fc60988d.png)

example test
![image](https://user-images.githubusercontent.com/98812101/178465387-988a5968-27c5-45f9-a224-02ba7c323f36.png)

Run the test and Test file can not be found and it create a new file located as `/app/src/components/category/categorycontainer.test.js` instead.
![image](https://user-images.githubusercontent.com/98812101/178464288-426b942d-a8cd-468e-8fc6-b2495347e314.png)

**Expected behavior**
Test file can be found and run the test.

**Environment**

- OS: Windows 10 running in DevContainer 
- VSCode version: 1.69.0
- Vitest version: 0.18.0
- Vitest plugin version: v0.2.20

**Comment by zxch3n** [comment]
Does it work now in the pre-release version?

**Comment by anbraten** [comment]
Tested and seems to work for me. Thanks.

**Comment by zxch3n** [comment]
Thank you @anbraten @YPetremann

**Comment by jtamyrc** [comment]
@zxch3n @anbraten  It still cannot find the test file if the directory contains uppercase characters, but it did fix the file contains uppercase characters. 

I tested in the preview version.

Please reopen this issue.
