### ISSUE TITLE
Extension fails to fetch dynamically imported module

### ISSUE THREAD

**Issue by dlims** [vitest-dev/vscode#544]
### Describe the bug

Tests launched from test explorer in browser mode fail to load extension module.

### Reproduction

Just trying to run a test in browser mode from test explorer produces this error: 

TypeError: Failed to fetch dynamically imported module: http://localhost:63315/@fs/C:/Users/dlore/.vscode/extensions/vitest.explorer-1.8.1/dist/setupFile.mjs?import&browserv=1732438481928

### Output

[11:01:08 AM] Initiating deferred test run
[INFO 11:01:08 AM] Running 1 file(s): src/core/unit-test-browser/VitestBrowserExample.spec.browser.ts
[11:01:08 AM] The runner is starting because tests src/core/unit-test-browser/VitestBrowserExample.spec.browser.ts were started due to a file change
[INFO 11:01:08 AM] [Worker] The request url "C:/Users/dlore/.vscode/extensions/vitest.explorer-1.8.1/dist/setupFile.mjs" is outside of Vite serving allow list
[Error 11:01:08 AM] Error in C:/Users/dlore/Github/bauhaus_master/src/core/unit-test-browser/VitestBrowserExample.spec.browser.ts TypeError: Failed to fetch dynamically imported module: http://localhost:63315/@fs/C:/Users/dlore/.vscode/extensions/vitest.explorer-1.8.1/dist/setupFile.mjs?import&browserv=1732615268915
[11:01:08 AM] Marking "VitestBrowserExample.spec.browser.ts [browser]" as failed with 1 errors
[11:01:08 AM] Marking "VitestBrowserExample.spec.browser.ts [browser]" as failed with 1 errors
[11:01:08 AM] Ending test run src/core/unit-test-browser/VitestBrowserExample.spec.browser.ts
[11:01:09 AM] [VSCODE] Ignoring file: node_modules\.vite\vitest\bcfb0f9579ecec702e2da1067b249218\results.json

### Version

Vitest Explorer: 1.8.1
Vite: 5.4.10
Vitest: 2.1.5

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dlims** [comment]
The same test launched from script works properly

**Comment by PPDEMOone** [comment]
I have the same problem.

**Comment by sheremet-va** [comment]
The "Output" field in this issue is not correct. It prints much more information, please don't crop it.

**Comment by sheremet-va** [comment]
I will add "needs reproduction" label, but more output should be enough. I also need to know Vite and Vitest versions.

**Comment by dlims** [comment]
> I will add "needs reproduction" label, but more output should be enough. I also need to know Vite and Vitest versions.

I've added requested info.

**Comment by kayahr** [comment]
Maybe this is some incompatibility to latest vitest or vitest/browser? I suddenly have the same problem in all my projects, so I tested it in a small demo project I created for a past issue:

https://github.com/kayahr/vitest-bugs-4

This demo project uses vitest 2.1.4 and I can't reproduce the problem there. But when I update vitest and vitest-browser dependency to 2.1.6 and restart vscode (or reload the tests) then I get the error:

![image](https://github.com/user-attachments/assets/6552a496-5ac7-4ee0-8550-fee042812c30)

Downgrading to 2.1.4 fixes the problem. With 2.1.5 it also doesn't work so I guess the problem was introduced in vitest 2.1.5. Or vitest/browser 2.1.5 (as only the browser tests are affected)

**Comment by bmthd** [comment]
I am facing the same problem with Vite 6.0.1,Vitest 2.1.5 and 2.1.6.
I am getting around this problem by fixing the version at 2.1.4.

**Comment by jpzwarte** [comment]
New vitest user here, but i can also confirm it works with 2.1.4 and not 2.1.6.

**Comment by sheremet-va** [comment]
Does this only happen with the browser mode?
