### ISSUE TITLE
Unable to install vitest-ext-basic-example on Ubuntu 20.04/WSL2/Node v18.5.0

### ISSUE THREAD

**Issue by CaliViking** [vitest-dev/vscode#59]
**Describe the bug**
Running `node setup.mjs` as described in https://github.com/zxch3n/vitest-ext-basic-example fails with error message:
`/bin/sh: 1: /mnt/c/Users/niels/AppData/Local/Programs/Microsoft: not found
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`

**To Reproduce**
1. Run `npm install yarn -g`
2. Follow instructions in https://github.com/zxch3n/vitest-ext-basic-example
3. Step 2 in step 2 above will fail

**Expected behavior**
Installation will work as described in https://github.com/zxch3n/vitest-ext-basic-example

**Screenshots**
![image](https://user-images.githubusercontent.com/3241878/179637423-da6bc6aa-80ff-48f8-9ba5-ed3192714f80.png)

**Environment**
Host Name:                 DESKTOP-XXXXXX
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          xxx.xxx@outlook.com
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA030
Original Install Date:     3/26/2022, 4:21:27 PM
System Boot Time:          7/14/2022, 2:51:17 AM
System Manufacturer:       Dell Inc.
System Model:              XPS 15 9570
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2208 Mhz
BIOS Version:              Dell Inc. 1.24.0, 3/21/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     32,502 MB
Available Physical Memory: 8,882 MB
Virtual Memory: Max Size:  52,982 MB
Virtual Memory: Available: 11,552 MB
Virtual Memory: In Use:    41,430 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-XXXXXX
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5013889
                           [02]: KB5007575
                           [03]: KB5015814
                           [04]: KB5016353
Network Card(s):           3 NIC(s) Installed.
                           [01]: DisplayLink Network Adapter NCM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.239
                                 [02]: fe80::8199:a49a:663a:8413
                           [02]: Killer Wireless-n/a/ac 1535 Wireless Network Adapter
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected

WSL: Linux DESKTOP-XXXXXXX 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

vitest/0.18.1 linux-x64 node-v18.5.0

**Comment by harsh123-baba** [comment]
I am also facing same issue while running multiple async process but they are independent from each other then i am getting error i am also confused in terms of i put all awaits but after one execution i am getting error

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
