### ISSUE TITLE
Test file cannot be found if the directory contains uppercase characters.

### ISSUE THREAD

**Issue by jtamyrc** [vitest-dev/vscode#65]
**Describe the bug**
Test file cannot be found if the directory contains uppercase characters.

Related issue: #54 but it didn't fix if the directory contains uppercase characters.

For example,
If the test file located in Category directory, such as `/app/src/components/Category/CategoryContainer.test.js`, the test file cannot be found.

**To Reproduce**
Click the test button if the directory contains uppercase characters.

**Screenshots**
test file and directory setup
![image](https://user-images.githubusercontent.com/98812101/178464104-62582312-0ad8-43d6-8860-a3c3fc60988d.png)

example test
![image](https://user-images.githubusercontent.com/98812101/178465387-988a5968-27c5-45f9-a224-02ba7c323f36.png)

Run the test and Test file can not be found and it create a new file located as `/app/src/components/category/categorycontainer.test.js` instead.
![image](https://user-images.githubusercontent.com/98812101/178464288-426b942d-a8cd-468e-8fc6-b2495347e314.png)

**Expected behavior**
Test file can be found and run the test.

**Environment**

- OS: Windows 10 running in DevContainer 
- VSCode version: 1.69.0
- Vitest version: 0.18.0
- Vitest plugin version: v0.2.20

**Comment by sheremet-va** [comment]
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
