### ISSUE TITLE
How to disable rerun on save?

### ISSUE THREAD

**Issue by rad182** [vitest-dev/vscode#70]
It seems it automatically reruns the test file on file save even watch mode is off

**To Reproduce**
just save the test file

**Expected behavior**
Should not rerun on save because watch mode is off

**Screenshots**
![image](https://user-images.githubusercontent.com/71201/182778361-e2df557f-2fd8-4f18-a613-cd15796de4d7.png)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS m1
- VSCode version: 1.69.2
- Vitest version: ^0.12.6
- Vitest plugin version: v0.2.23

**Comment by zxch3n** [comment]
It won't rerun on save if it's not in the watch mode. Can you reproduce this issue stablely?

**Comment by rad182** [comment]
@zxch3n this happens when I change to "vitest.commandLine": "npx vitest" even for the example project
The reason I need to use `npx vitest` so I can add coverage so `npx vitest --coverage` since it seems the default one doesn't read the vite.config.ts that it should generate coverage.

**Comment by zxch3n** [comment]
Is this still happening on the latest version?

**Comment by luxaritas** [comment]
Correct me if I'm wrong, but I think the issue here is that this extension requires Vitest to be run in watch mode (due to its reliance on the API), but when the test run finishes, the watch process is never closed - that's what I see on my end.

**Comment by luxaritas** [comment]
Hm, actually I guess not - looks like that was a stale process from a point where I had commandLine set incorrectly. Disregard, I suppose!
