### ISSUE TITLE
Rename a file only changing the case causes the test to be listed twice.

### ISSUE THREAD

**Issue by grantmcdade** [vitest-dev/vscode#76]
**Describe the bug**
Renaming app.test.ts to App.test.ts causes both to be listed in the explorer. They both have the same tests but all of the tests in app.test.ts fail with the text 'Are there tests with the same name?' among other things.

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/grantmcdade/my-vue-app):

1. Run the tests
2. Rename App.test.ts to app.test.ts
3. Run the tests

**Expected behavior**
App.test.ts is no longer on the list.

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: Windows
- VSCode version:
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043
- Vitest version: 0.22.0
- Vitest plugin version:
Name: Vitest
Id: ZixuanChen.vitest-explorer
Description: Run and debug Vitest test cases
Version: 0.2.24
Publisher: Zixuan Chen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer

**Comment by huwshimi** [comment]
It looks like this might not be an issue anymore (tested with v0.2.42).

Before rename:

<img width="291" alt="Screenshot 2023-10-18 at 5 35 23 pm" src="https://github.com/vitest-dev/vscode/assets/361637/1aed3d83-d8d9-4f0e-bb2a-6a7ff7cd3d20">

After rename:

<img width="295" alt="Screenshot 2023-10-18 at 5 35 39 pm" src="https://github.com/vitest-dev/vscode/assets/361637/08d041d1-2cdf-4d1e-bc39-a7dfbc2611ae">

**Comment by grantmcdade** [comment]
Thanks, I'll close the issue then.
