### ISSUE TITLE
Vitest VSCode extension doesn't give information about test files written in another language

### ISSUE THREAD

**Issue by haikyuu** [vitest-dev/vscode#82]
**Describe the bug**
I'm writing my test files using Imba. I'm using the Imba plugin for Vite, so Vite and vitest handle them correctly.
But I only see the file name in the tests pane.

**To Reproduce**
Steps to reproduce the behavior on [this example project](https://github.com/imba/imba-vite-template):

1. Run tests in the extension
2. You will only see the test files

**Expected behavior**
I would like to actually display the details from the test file

**Screenshots**
<img width="825" alt="image" src="https://user-images.githubusercontent.com/8558836/189283266-7f416fee-32d6-4de6-86b2-573156594f55.png">

## How to?
I'm not sure about how you analyze the test files. But it would work if the extension analyzes the transformed files instead.

**Comment by ColinKrist** [comment]
I've opened up your sample repo - under `settings.json` you need to configure `vitest.include` to include the file extensions of these files. The defaults are mentioned here: https://github.com/vitest-dev/vscode#config, and most notably don't include imba.

**Comment by haikyuu** [comment]
Let me explain, here is a test and its exact compiled version

Imba includes sourcemaps with the compiled code, so they should be picked up by the extension

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/8558836/189473204-ac798ace-90df-443f-855d-022690e20df6.png">

**Comment by haikyuu** [comment]
I just found out that [the extension uses babel](https://github.com/vitest-dev/vscode/blob/main/src/pure/parsers/babel_parser.ts) to parse files and not Vite. 

In order to support this feature, I believe we could hook into Vitest which already provides this information ([example here](https://github.com/sapphi-red/vitest-github-actions-reporter/pull/2/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R126) that gets sourcemaps in the context of a reporter) instead of parsing files using babel.

**Comment by jmagaram** [comment]
Probably related to my similar issue of tests written in ReScript.

https://github.com/vitest-dev/vscode/issues/127

**Comment by sheremet-va** [comment]
This is now supported in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
