### ISSUE TITLE
Define path to package.json

### ISSUE THREAD

**Issue by daribock** [vitest-dev/vscode#85]
**Is your feature request related to a problem? Please describe.**
The project I am working on uses kotlin for the backend and therefore the ui is in a seperate folder and the package.json is therefore not in the root of the project. This is why I am getting errors when running the tests.
![image](https://user-images.githubusercontent.com/57658125/190590508-c6b3c172-142e-44f5-a593-c0c0eece2514.png)

**Describe the solution you'd like**
My suggestion for this solution would be either one of these two options:

1. Auto detect package.json
2. Option to manually define the path to package.json

**Comment by l30ni3** [comment]
Is there any update on how to run the vitest runner, if the web folder is not in root?

**Comment by zxch3n** [comment]
You can try using VS Code workspace as a workaround for now

**Comment by zxch3n** [comment]
Close this in favor of #101
