### ISSUE TITLE
Extension Host terminated unexpectedlly

### ISSUE THREAD

**Issue by safie** [vitest-dev/vscode#91]
Type: <b>Bug</b>

using Extension Bisect to detect

Extension version: 0.2.29
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (8.18GB free)|
|Process Argv|--crash-reporter-id 041e2c60-4f8f-4a07-8800-1e8ab13845e5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by fictitious** [comment]
it looks like node crashed when running vitest.

possibly related: https://github.com/nodejs/node/issues/6899#issuecomment-1210954352, https://github.com/nodejs/node/issues/43304#issuecomment-1239001374

also can happen when there's a test file which does not have any tests - I had node crashed after this vitest error

>  FAIL  src/t2.test.ts [ src/t2.test.ts ]
> Error: No test suite found in file /src/t2.test.ts

seems like it's node or vitest issue, not caused by this extension directly - could you try to see if the crash happens when you run tests from command line, not in vs code ?

**Comment by zxch3n** [comment]
Is this still happening?

**Comment by sabithakuppusamy** [comment]
Yes, I am facing this issue with Vitest 0.25.8 and node v18.0.0

**Comment by MilanKovacic** [comment]
New version of extension has been released on https://marketplace.visualstudio.com/items?itemName=vitest.explorer. Please try it out, and if the issue still persists, feel free to open a new one.
