### ISSUE TITLE
Tests run forever, console spams "WS close" endlessly

### ISSUE THREAD

**Issue by c00** [vitest-dev/vscode#92]
**Describe the bug**
When running a test from the test runner, the test starts (the circles start turning), but never finishes.

When checking the console output of vitest, I can see the test running and  completing successfully, but the console is also flooded with the message "WS close" about 20x per second.

(I assume some websocket connection is attempted, causing the plugin never to get the results back, but this is pure layman speculation)

**To Reproduce**
- Clone [this repo](https://github.com/c00/vitest-bug-ws-close), `npm install`
- Open it in VS code
- Open the vitest console output
- Go to the test-runner and run the test.
- See the console being flooded with errors.

**Expected behavior**
I expect the test to run to completion and the test-runner to report on the result.

**Screenshots**
![vitest sadness](https://user-images.githubusercontent.com/6259056/194102903-40203e24-b248-4506-b9e3-5bbebca1a1e1.gif)

**Environment**

[Full details here](https://github.com/c00/vitest-bug-ws-close#bug-report-for-vitest)

- OS: Fedora 36, KDE Plasma
- VSCode version: 1.71.2
- Vitest version: 0.23.4
- Vitest plugin version: 0.2.29

**Additional context**

Console output:

```
[INFO 10:44:30 PM] Vitest Workspace [vitest-bug-ws-close]: Vitest version = 0.23.4
[INFO 10:46:51 PM] Tests run start
[INFO 10:46:51 PM] [Workspace "vitest-bug-ws-close] Run tests from workspace
[INFO 10:46:51 PM] [Execute Vitest] /home/coo/dev/vitest-bug-ws-close/node_modules/.bin/vitest /home/coo/dev/vitest-bug-ws-close/src/foo.spec.ts -t things anything
[INFO 10:46:51 PM] Start api process at port 35053
[INFO 10:46:51 PM] [RUN] /home/coo/dev/vitest-bug-ws-close/node_modules/.bin/vitest /home/coo/dev/vitest-bug-ws-close/src/foo.spec.ts -t things anything
[INFO 10:46:51 PM] [RUN.cwd] /home/coo/dev/vitest-bug-ws-close
[INFO 10:46:51 PM] WS Close
<The same log message truncated>
[INFO 10:46:52 PM] WS Close
[INFO 10:46:52 PM] 

 DEV  v0.23.4 /home/coo/dev/vitest-bug-ws-close

      API started at http://localhost:35053

[INFO 10:46:52 PM] WS Close
<The same log message truncated>
[INFO 10:46:53 PM] WS Close
[INFO 10:46:53 PM]  ✓ src/foo.spec.ts  (1 test) 2ms

Test Files  1 passed (1)

     Tests  1 passed (1)

  Start at  22:46:52

  Duration  947ms (transform 300ms, setup 67ms, collect 7ms, tests 2ms)

 PASS  Waiting for file changes...

       press h to show help, press q to quit

[INFO 10:46:53 PM] WS Close
[INFO 10:46:53 PM] WS Close
[INFO 10:46:53 PM] WS Close
<many more of these>
```

When manually running `npm run test`, there are no errors.

**Comment by DaiKnapz** [comment]
I had the same issue, it may be a configureation issue, see [this issue](https://github.com/vitest-dev/vscode/issues/55#issuecomment-1231161530) for more details.

For me all it took was adding -- to the end of my vitest.commandLine configuration
<img width="1129" alt="Screenshot 2022-10-05 at 23 27 06" src="https://user-images.githubusercontent.com/7976546/194175356-db4ea528-2ccf-47d7-bb87-429f4c6bb3c0.png">

**Comment by c00** [comment]
Thank you @DaiKnapz . This gets me somewhat further. Now instead of running endlessly, it always finishes with the error:

```
[Error 7:57:02 AM] Test not found: file:///home/coo/dev/vitest-bug-ws-close/src/foo.spec.ts/things anything@1
```

So, yes, indeed it was misconfigured because vitest by default runs in watch mode which the plugin does not work with. For me I changes the setting you shown to `npx vitest --run` to force it to quit after it's done. 

The full error at the end is now:

```
[INFO 7:57:02 AM] API PROCESS EXIT
[INFO 7:57:02 AM] Vitest api process finished
[Error 7:57:02 AM] Test not found: file:///home/coo/dev/vitest-bug-ws-close/src/foo.spec.ts/things anything@1
[INFO 7:57:02 AM] [Workspace "vitest-bug-ws-close] Test run finished
[INFO 7:57:02 AM] Tests run end
[Error 7:57:02 AM] 
Failed to get any result
( Vitest should be configured to be able to run from project root )

Error when running
    npx vitest --run /home/coo/dev/vitest-bug-ws-close/src/foo.spec.ts -t things anything

cwd: /home/coo/dev/vitest-bug-ws-close
node: v18.7.0

env.PATH: /home/coo/.local/share/pnpm:/home/coo/.asdf/shims:/home/coo/.asdf/bin:/home/coo/.local/share/pnpm:/home/coo/.local/bin:/home/coo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

[Error 7:57:02 AM] 

 RUN  v0.23.4 /home/coo/dev/vitest-bug-ws-close

      API started at http://localhost:45615



 ✓ src/foo.spec.ts  (1 test) 2ms



Test Files  1 passed (1)

     Tests  1 passed (1)

  Start at  07:57:00

  Duration  1.44s (transform 393ms, setup 113ms, collect 8ms, tests 2ms)



[INFO 7:57:02 AM] WS Close
[INFO 7:57:02 AM] WS Close
```

**Comment by beorn** [comment]
Duplicate of #55 ?

**Comment by c00** [comment]
I don't think it is for 2 reasons:

1. Following the instructions in that thread, it does not resolve my issue.
2. My primary finding is the "WS Close" log messages (without ever having a "WS Open" log message, which is not mentioned at all in the other thread.

**Comment by c00** [comment]
Duplicate of https://github.com/vitest-dev/vscode/issues/55
