### ISSUE TITLE
Invalid Chai property: toHaveFetched

### ISSUE THREAD

**Issue by Xa3lis** [vitest-dev/vscode#95]
**Describe the bug**
On my project i use [vi-fetch](https://github.com/sheremet-va/vi-fetch) which add matchers to the actual chai ones, it is well configured in the setup file (aka: When i launch the tests using vitest CLI it runs perfectly)
But when I use the extension, i got an error message `Invalid Chai property: toHaveFetched`

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Install `vi-fetch`
2. Make a test containing `expect(xxx).toHaveFetched()`
3. See error

**Expected behavior**
The same behavior I have in vitest CLI

**Screenshots**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/8726129/196438336-dbaf012b-31fe-4a21-b003-4b0c9418529c.png">

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS
- VSCode version: 1.72.1
- Vitest version: 0.24.1
- Vitest plugin version: 0.2.32

**Additional context**

**Comment by sheremet-va** [comment]
This should be fixed already.
