### ISSUE TITLE
Playwright tests being run as Vitest

### ISSUE THREAD

**Issue by Nithos** [vitest-dev/vscode#96]
**Describe the bug**
There seems to be an issue with Playwright tests being run under the vitest runner when using the extension plugin. Specifically when dealing with the Playwright component tests.

Our setup includes 
Vitest - for unit testing
Playwright - for e2e testing
Playwright CT - for component testing

Explicit exclusion of component tests are set in the `vite.config.ts` file with the following
```
test: {
	exclude: [...configDefaults.exclude, '**/tests/component/**']
}
```

There are 2 main issues we are seeing.

1. Tests from Playwright are also shown in the vitest section of the test explorer (see screenshot). Although when using the test explorer to run all the vitest tests they seem to be ignored (still see the spinner of them running but no errors, just the red failure dot for the test).

2. When trying to run a playwright component test from within the file (by clicking the green run tests) it seems to invoke the vitest runner instead throwing an error. 
```
Test result not found. 
If you set `vitest.commandLine` please check: 
    Did you set `vitest.commandLine` to `run` mode? (This extension requires `watch` mode to get the results from Vitest api)
    Does it have the ability to append extra arguments? (For example it should be `yarn test --` rather than `yarn test`)
Are there tests with the same name?
Can you run vitest successfully on this file? Does it need custom option to run?


Vitest output:
[vitest] Error, while trying to parse cache in /---/node_modules/.vitest/results.json: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ResultsCache.readFromCache (file:///---/node_modules/vitest/dist/chunk-vite-node-externalize.94f78ce5.js:8719:51)
    at async Vitest.setServer (file:///---/node_modules/vitest/dist/chunk-vite-node-externalize.94f78ce5.js:9808:7)
    at async configureServer (file:///---/node_modules/vitest/dist/chunk-vite-node-externalize.94f78ce5.js:10558:11)
    at async createServer (file:///---/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:62251:24)
    at async createVitest (file:///---/node_modules/vitest/dist/chunk-vite-node-externalize.94f78ce5.js:10590:18)
    at async startVitest (file:///---/node_modules/vitest/dist/chunk-vite-node-externalize.94f78ce5.js:10698:15)
    at async start (file:///---/node_modules/vitest/dist/cli.js:679:9)

 DEV  v0.24.1 /---
      API started at http://127.0.0.1:54554

 ❯ packages/client/webapp/tests/component/model-sidebar-panel.spec.ts  (0 test)

```

**Expected behavior**
Vitest should not be run on non vitest tests

**Screenshots**
<img width="519" alt="image" src="https://user-images.githubusercontent.com/2914422/197029539-35105fae-4f7a-4dee-acb3-ebe6e2bdfecb.png">

**Environment**

- OS: macOS
- VSCode: 1.72.2 
- Vitest version: 0.24.1
- Vitest plugin version: 0.2.32

**Comment by jacknevitt** [comment]
I am also seeing the extension include playwright tests, although they have been excluded in vitest.config.ts.

![Screenshot 2022-11-10 at 10 53 48](https://user-images.githubusercontent.com/19165624/201072649-016373d3-1a41-4fbb-9dcf-f587ebb35261.png)

**Comment by porfirioribeiro** [comment]
To solve this issue, I've added on my VS code settings
```json

    "vitest.exclude": ["**/node_modules/**", "**/dist/**", "**/e2e/**", "**/.{idea,git,cache,output,temp}/**"],

```

**Comment by xmlking** [comment]
> To solve this issue, I've added on my VS code settings
> 
> ```json
>     "vitest.exclude": ["**/node_modules/**", "**/dist/**", "**/e2e/**", "**/.{idea,git,cache,output,temp}/**"],
> ```

this is not working if you click `Refresh Tests` button

**Comment by JackNeto** [comment]
> > To solve this issue, I've added on my VS code settings
> > ```json
> >     "vitest.exclude": ["**/node_modules/**", "**/dist/**", "**/e2e/**", "**/.{idea,git,cache,output,temp}/**"],
> > ```
> 
> this is not working if you click `Refresh Tests` button

Confirming that this is still not working for me either

**Comment by opack** [comment]
I ran into the exact same problem and found the same solution. But I still don't understand why this extension does not rely on the vitest config file (either `vitest.config.ts` or the `test` section of the `vite.config.ts` file) if it exists. I think that the values in the extension settings should only be used if there is no official Vitest config in the project (or if a settings tells the extension to ignore it).
