### ISSUE TITLE
Setup guide for pnpm workspace users

### ISSUE THREAD

**Issue by jasonkuhrt** [vitest-dev/vscode#99]
I'm having trouble getting this to work with a pnpm workspace. If any users out there get a good flow going would be nice to document it. Also probably some missing features as well to improve support. One thing I've done that seems to be working ish, is to open a package within the monorepo as a new VSCode workspace/window.

**Comment by hidde-jan** [comment]
Same issue as #81, which also hasn’t gotten a response.

**Comment by jasonkuhrt** [comment]
Thanks @hidde-jan
